Line [Parent]            Text
1    [FUNC_PROTO]        static
1    [FUNC_PROTO]        int32_t
1    [NONE]              level_and_name_to_system
1    [FUNC_PROTO]        (
1    [NONE]              SocketOptionLevel
1    [NONE]              level
1    [NONE]              ,
1    [NONE]              SocketOptionName
1    [NONE]              name
1    [NONE]              ,
1    [NONE]              int32_t
1    [NONE]              *
1    [NONE]              system_level
1    [NONE]              ,
1    [NONE]              int32_t
1    [NONE]              *
1    [NONE]              system_name
1    [FUNC_PROTO]        )
1    [NONE]              
3    [FUNC_PROTO]        WaitStatus
3    [NONE]              SendTo
3    [FUNC_PROTO]        (
3    [NONE]              uint8_t
3    [NONE]              address
3    [NONE]              [
3    [NONE]              ipv6AddressSize
3    [NONE]              ]
3    [NONE]              ,
3    [NONE]              uint32_t
3    [NONE]              scope
3    [NONE]              ,
3    [NONE]              uint16_t
3    [NONE]              port
3    [NONE]              ,
3    [NONE]              const
3    [NONE]              uint8_t
3    [NONE]              *
3    [NONE]              data
3    [NONE]              ,
3    [NONE]              int32_t
3    [NONE]              count
3    [NONE]              ,
3    [NONE]              os
3    [NONE]              ::
3    [NONE]              SocketFlags
3    [NONE]              flags
3    [NONE]              ,
3    [NONE]              int32_t
3    [NONE]              *
3    [NONE]              len
3    [FUNC_PROTO]        )
3    [FUNC_PROTO]        ;
3    [NONE]              