Line [Parent]            Text
1    [COMMENT_WHOLE]     //It is applying double indentation
1    [NONE]              
2    [NONE]              m_ApplicationView
2    [NONE]              =
2    [NONE]              AppC
2    [NONE]              ::
2    [NONE]              ApplicationView
2    [NONE]              ::
2    [NONE]              GetForCurrentView
2    [FUNC_CALL]         (
2    [FUNC_CALL]         )
2    [NONE]              ;
2    [NONE]              
3    [NONE]              m_ViewConsolidateEvtToken
3    [NONE]              =
3    [NONE]              m_ApplicationView
3    [NONE]              ->
3    [NONE]              Consolidated
3    [NONE]              +=
3    [NONE]              
4    [NONE]              ref
4    [NONE]              new
4    [NONE]              AppC
4    [NONE]              ::
4    [NONE]              TypedEventHandler
4    [TEMPLATE]          <
4    [NONE]              AppC
4    [NONE]              ::
4    [NONE]              ApplicationView
4    [NONE]              ^
4    [NONE]              ,
4    [NONE]              AppC
4    [NONE]              ::
4    [NONE]              ApplicationViewConsolidatedEventArgs
4    [NONE]              ^
4    [TEMPLATE]          >
4    [FUNC_CALL]         (
4    [NONE]              this
4    [NONE]              ,
4    [NONE]              &
4    [NONE]              FrameworkView
4    [NONE]              ::
4    [NONE]              InternalOnViewConsolidated
4    [FUNC_CALL]         )
4    [NONE]              ;
4    [NONE]              
6    [NONE]              m_WindowActivatedEvtToken
6    [NONE]              =
6    [NONE]              m_CoreWindow
6    [NONE]              ->
6    [NONE]              Activated
6    [NONE]              +=
6    [NONE]              
7    [NONE]              ref
7    [NONE]              new
7    [NONE]              AppC
7    [NONE]              ::
7    [NONE]              TypedEventHandler
7    [TEMPLATE]          <
7    [NONE]              AppC
7    [NONE]              ::
7    [NONE]              CoreWindow
7    [NONE]              ^
7    [NONE]              ,
7    [NONE]              AppC
7    [NONE]              ::
7    [NONE]              WindowActivatedEventArgs
7    [NONE]              ^
7    [TEMPLATE]          >
7    [FUNC_CALL]         (
7    [NONE]              this
7    [NONE]              ,
7    [NONE]              &
7    [NONE]              FrameworkView
7    [NONE]              ::
7    [NONE]              InternalOnWindowActivated
7    [FUNC_CALL]         )
7    [NONE]              ;
7    [NONE]              
9    [NONE]              m_SizeChangedEvtToken
9    [NONE]              =
9    [NONE]              m_CoreWindow
9    [NONE]              ->
9    [NONE]              SizeChanged
9    [NONE]              +=
9    [NONE]              
10   [NONE]              ref
10   [NONE]              new
10   [NONE]              AppC
10   [NONE]              ::
10   [NONE]              TypedEventHandler
10   [TEMPLATE]          <
10   [NONE]              AppC
10   [NONE]              ::
10   [NONE]              CoreWindow
10   [NONE]              ^
10   [NONE]              ,
10   [NONE]              AppC
10   [NONE]              ::
10   [NONE]              WindowSizeChangedEventArgs
10   [NONE]              ^
10   [TEMPLATE]          >
10   [FUNC_CALL]         (
10   [NONE]              this
10   [NONE]              ,
10   [NONE]              &
10   [NONE]              FrameworkView
10   [NONE]              ::
10   [NONE]              InternalOnWindowSizeChanged
10   [FUNC_CALL]         )
10   [NONE]              ;
10   [NONE]              
12   [NONE]              m_VisibilityChangedEvtToken
12   [NONE]              =
12   [NONE]              m_CoreWindow
12   [NONE]              ->
12   [NONE]              VisibilityChanged
12   [NONE]              +=
12   [NONE]              
13   [NONE]              ref
13   [NONE]              new
13   [NONE]              AppC
13   [NONE]              ::
13   [NONE]              TypedEventHandler
13   [TEMPLATE]          <
13   [NONE]              AppC
13   [NONE]              ::
13   [NONE]              CoreWindow
13   [NONE]              ^
13   [NONE]              ,
13   [NONE]              AppC
13   [NONE]              ::
13   [NONE]              VisibilityChangedEventArgs
13   [NONE]              ^
13   [TEMPLATE]          >
13   [FUNC_CALL]         (
13   [NONE]              this
13   [NONE]              ,
13   [NONE]              &
13   [NONE]              FrameworkView
13   [NONE]              ::
13   [NONE]              InternalOnWindowVisibilityChanged
13   [FUNC_CALL]         )
13   [NONE]              ;
13   [NONE]              
15   [NONE]              m_WindowClosedEvtToken
15   [NONE]              =
15   [NONE]              m_CoreWindow
15   [NONE]              ->
15   [NONE]              Closed
15   [NONE]              +=
15   [NONE]              
16   [NONE]              ref
16   [NONE]              new
16   [NONE]              AppC
16   [NONE]              ::
16   [NONE]              TypedEventHandler
16   [TEMPLATE]          <
16   [NONE]              AppC
16   [NONE]              ::
16   [NONE]              CoreWindow
16   [NONE]              ^
16   [NONE]              ,
16   [NONE]              AppC
16   [NONE]              ::
16   [NONE]              CoreWindowEventArgs
16   [NONE]              ^
16   [TEMPLATE]          >
16   [FUNC_CALL]         (
16   [NONE]              this
16   [NONE]              ,
16   [NONE]              &
16   [NONE]              FrameworkView
16   [NONE]              ::
16   [NONE]              InternalOnWindowClosed
16   [FUNC_CALL]         )
16   [NONE]              ;
16   [NONE]              