Line [Parent]            Text
1    [FUNC_VAR]          void
1    [FUNC_VAR]          (
1    [NONE]              *
1    [NONE]              foo
1    [FUNC_VAR]          )
1    [FUNC_PROTO]        (
1    [NONE]              int
1    [FUNC_PROTO]        )
1    [FUNC_VAR]          ;
1    [NONE]              
2    [NONE]              static
2    [NONE]              bar
2    [FUNC_CALL]         (
2    [NONE]              void
2    [FUNC_VAR]          (
2    [NONE]              *
2    [NONE]              foo
2    [FUNC_VAR]          )
2    [FUNC_CALL]         (
2    [NONE]              int
2    [FUNC_CALL]         )
2    [FUNC_CALL]         )
2    [NONE]              
3    [FUNC_CALL]         {
3    [NONE]              
4    [FUNC_CALL]         }
4    [NONE]              
6    [FUNC_VAR]          bool
6    [FUNC_VAR]          (
6    [NONE]              *
6    [NONE]              comp_func
6    [FUNC_VAR]          )
6    [FUNC_PROTO]        (
6    [NONE]              const
6    [NONE]              TypeA
6    [NONE]              *
6    [NONE]              const
6    [NONE]              a
6    [NONE]              ,
6    [NONE]              const
6    [NONE]              TypeB
6    [NONE]              &
6    [NONE]              value
6    [FUNC_PROTO]        )
6    [NONE]              =
6    [NONE]              NULL
6    [NONE]              ;
6    [NONE]              
7    [NONE]              static
7    [NONE]              foo
7    [FUNC_CALL]         (
7    [NONE]              bool
7    [FUNC_VAR]          (
7    [NONE]              *
7    [NONE]              comp_func
7    [FUNC_VAR]          )
7    [FUNC_CALL]         (
7    [NONE]              const
7    [NONE]              TypeA
7    [NONE]              *
7    [NONE]              const
7    [NONE]              a
7    [NONE]              ,
7    [NONE]              const
7    [NONE]              TypeB
7    [NONE]              &
7    [NONE]              value
7    [FUNC_CALL]         )
7    [FUNC_CALL]         )
7    [NONE]              ;
7    [NONE]              
8    [NONE]              static
8    [NONE]              foo
8    [FUNC_CALL]         (
8    [NONE]              bool
8    [FUNC_VAR]          (
8    [NONE]              *
8    [NONE]              comp_func
8    [FUNC_VAR]          )
8    [FUNC_CALL]         (
8    [NONE]              const
8    [NONE]              TypeA
8    [NONE]              *
8    [NONE]              const
8    [NONE]              a
8    [NONE]              ,
8    [NONE]              const
8    [NONE]              TypeB
8    [NONE]              &
8    [NONE]              value
8    [FUNC_CALL]         )
8    [NONE]              =
8    [NONE]              NULL
8    [FUNC_CALL]         )
8    [NONE]              
9    [FUNC_CALL]         {
9    [NONE]              
10   [FUNC_CALL]         }
10   [NONE]              
12   [FUNC_PROTO]        void
12   [NONE]              qsort
12   [FUNC_PROTO]        (
12   [NONE]              void
12   [NONE]              *
12   [NONE]              base
12   [NONE]              ,
12   [NONE]              size_t
12   [NONE]              nmemb
12   [NONE]              ,
12   [NONE]              size_t
12   [NONE]              size
12   [NONE]              ,
12   [NONE]              int
12   [FUNC_VAR]          (
12   [NONE]              *
12   [NONE]              compar
12   [FUNC_VAR]          )
12   [FUNC_CALL]         (
12   [NONE]              const
12   [NONE]              TypeA
12   [NONE]              *
12   [NONE]              lhs
12   [NONE]              ,
12   [NONE]              const
12   [NONE]              TypeB
12   [NONE]              &
12   [NONE]              rhs
12   [FUNC_CALL]         )
12   [FUNC_PROTO]        )
12   [FUNC_PROTO]        ;
12   [NONE]              
13   [FUNC_DEF]          void
13   [NONE]              qsort
13   [FUNC_DEF]          (
13   [NONE]              void
13   [NONE]              *
13   [NONE]              base
13   [NONE]              ,
13   [NONE]              size_t
13   [NONE]              nmemb
13   [NONE]              ,
13   [NONE]              size_t
13   [NONE]              size
13   [NONE]              ,
13   [FUNC_VAR]          int
13   [FUNC_VAR]          (
13   [NONE]              *
13   [NONE]              compar
13   [FUNC_VAR]          )
13   [FUNC_PROTO]        (
13   [NONE]              const
13   [NONE]              TypeA
13   [NONE]              *
13   [NONE]              lhs
13   [NONE]              ,
13   [NONE]              const
13   [NONE]              TypeB
13   [NONE]              &
13   [NONE]              rhs
13   [FUNC_PROTO]        )
13   [FUNC_PROTO]        =
13   [NONE]              NULL
13   [FUNC_DEF]          )
13   [NONE]              
14   [FUNC_DEF]          {
14   [NONE]              
15   [FUNC_DEF]          }
15   [NONE]              