Line [Parent]            Text
1    [NONE]              byte
1    [NONE]              []
1    [NONE]              utf8Str
1    [NONE]              =
1    [NONE]              new
1    [NONE]              byte
1    [NONE]              []
1    [NONE]              {
1    [NONE]              197
1    [NONE]              ,
1    [NONE]              170
1    [NONE]              ,
1    [NONE]              110
1    [NONE]              ,
1    [NONE]              196
1    [NONE]              ,
1    [NONE]              173
1    [NONE]              ,
1    [NONE]              099
1    [NONE]              ,
1    [NONE]              197
1    [NONE]              ,
1    [NONE]              141
1    [NONE]              ,
1    [NONE]              100
1    [NONE]              ,
1    [NONE]              101
1    [NONE]              ,
1    [NONE]              204
1    [NONE]              ,
1    [NONE]              189
1    [NONE]              }
1    [NONE]              ;
1    [NONE]              