Line [Token]             Text
1    [NEWLINE]           
2    [PREPROC]           #
2    [PP_DEFINE]         define
2    [MACRO_FUNC]        foobar
2    [FPAREN_OPEN]       (
2    [WORD]              x
2    [FPAREN_CLOSE]      )
2    [NL_CONT]           \
3    [BRACE_OPEN]        {
3    [NL_CONT]           \
4    [FOR]               for
4    [SPAREN_OPEN]       (
4    [WORD]              i
4    [ASSIGN]            =
4    [NUMBER]            0
4    [SEMICOLON]         ;
4    [WORD]              i
4    [COMPARE]           <
4    [WORD]              x
4    [SEMICOLON]         ;
4    [WORD]              i
4    [INCDEC_AFTER]      ++
4    [SPAREN_CLOSE]      )
4    [NL_CONT]           \
5    [BRACE_OPEN]        {
5    [NL_CONT]           \
6    [FUNC_CALL]         junk
6    [FPAREN_OPEN]       (
6    [WORD]              i
6    [COMMA]             ,
6    [WORD]              x
6    [FPAREN_CLOSE]      )
6    [SEMICOLON]         ;
6    [NL_CONT]           \
7    [BRACE_CLOSE]       }
7    [NL_CONT]           \
8    [BRACE_CLOSE]       }
8    [NEWLINE]           