Line [Token]             Text
1    [TYPE]              void
1    [FUNC_DEF]          foo
1    [FPAREN_OPEN]       (
1    [TYPE]              int
1    [PTR_TYPE]          *
1    [WORD]              pA
1    [COMMA]             ,
1    [TYPE]              int
1    [PTR_TYPE]          *
1    [WORD]              pB
1    [FPAREN_CLOSE]      )
1    [NEWLINE]           
2    [BRACE_OPEN]        {
2    [NEWLINE]           
3    [DEREF]             *
3    [WORD]              pB
3    [ASSIGN]            =
3    [WORD]              some
3    [MEMBER]            .
3    [WORD]              arr
3    [SQUARE_OPEN]       [
3    [DEREF]             *
3    [WORD]              pA
3    [SQUARE_CLOSE]      ]
3    [SEMICOLON]         ;
3    [NEWLINE]           
5    [FUNC_CALL]         foo
5    [FPAREN_OPEN]       (
5    [SIZEOF]            sizeof
5    [WORD]              bar
5    [ARITH]             /
5    [SIZEOF]            sizeof
5    [DEREF]             *
5    [WORD]              bar
5    [COMMA]             ,
5    [WORD]              baz
5    [FPAREN_CLOSE]      )
5    [SEMICOLON]         ;
5    [NEWLINE]           
7    [BRACE_CLOSE]       }
7    [NEWLINE]           
9    [PREPROC]           #
9    [PP_DEFINE]         define
9    [MACRO_FUNC]        MEM_READ_BYTE
9    [FPAREN_OPEN]       (
9    [WORD]              phwi
9    [COMMA]             ,
9    [WORD]              addr
9    [COMMA]             ,
9    [WORD]              data
9    [FPAREN_CLOSE]      )
9    [NL_CONT]           \
10   [DEREF]             *
10   [WORD]              data
10   [ASSIGN]            =
10   [DEREF]             *
10   [PAREN_OPEN]        (
10   [PAREN_OPEN]        (
10   [TYPE]              PUCHAR
10   [PAREN_CLOSE]       )
10   [PAREN_OPEN]        (
10   [PAREN_OPEN]        (
10   [WORD]              phwi
10   [PAREN_CLOSE]       )
10   [MEMBER]            ->
10   [WORD]              m_pVirtualMemory
10   [ARITH]             +
10   [WORD]              addr
10   [PAREN_CLOSE]       )
10   [PAREN_CLOSE]       )
10   [NEWLINE]           
12   [PREPROC]           #
12   [PP_DEFINE]         define
12   [MACRO_FUNC]        MEM_WRITE_BYTE
12   [FPAREN_OPEN]       (
12   [WORD]              phwi
12   [COMMA]             ,
12   [WORD]              addr
12   [COMMA]             ,
12   [WORD]              data
12   [FPAREN_CLOSE]      )
12   [NL_CONT]           \
13   [DEREF]             *
13   [PAREN_OPEN]        (
13   [PAREN_OPEN]        (
13   [TYPE]              PUCHAR
13   [PAREN_CLOSE]       )
13   [PAREN_OPEN]        (
13   [PAREN_OPEN]        (
13   [WORD]              phwi
13   [PAREN_CLOSE]       )
13   [MEMBER]            ->
13   [WORD]              m_pVirtualMemory
13   [ARITH]             +
13   [WORD]              addr
13   [PAREN_CLOSE]       )
13   [PAREN_CLOSE]       )
13   [ASSIGN]            =
13   [PAREN_OPEN]        (
13   [TYPE]              UCHAR
13   [PAREN_CLOSE]       )
13   [PAREN_OPEN]        (
13   [WORD]              data
13   [PAREN_CLOSE]       )
13   [NEWLINE]           