Line [Token]             Text
1    [PREPROC]           #
1    [PP_DEFINE]         define
1    [MACRO]             UHI_AOA
1    [BRACE_OPEN]        {
1    [NL_CONT]           \
2    [C99_MEMBER]        .
2    [WORD]              install
2    [ASSIGN]            =
2    [WORD]              uhi_aoa_install
2    [COMMA]             ,
2    [NL_CONT]           \
3    [C99_MEMBER]        .
3    [WORD]              enable
3    [ASSIGN]            =
3    [WORD]              uhi_aoa_enable
3    [COMMA]             ,
3    [NL_CONT]           \
4    [C99_MEMBER]        .
4    [WORD]              uninstall
4    [ASSIGN]            =
4    [WORD]              uhi_aoa_uninstall
4    [COMMA]             ,
4    [NL_CONT]           \
5    [C99_MEMBER]        .
5    [WORD]              sof_notify
5    [ASSIGN]            =
5    [WORD]              NULL
5    [COMMA]             ,
5    [NL_CONT]           \
6    [BRACE_CLOSE]       }
6    [NEWLINE]           