Line [Token]             Text
1    [TYPE]              void
1    [FUNC_PROTO]        foo1
1    [FPAREN_OPEN]       (
1    [TYPE]              int
1    [WORD]              param1
1    [COMMA]             ,
1    [TYPE]              int
1    [WORD]              param2
1    [COMMA]             ,
1    [TYPE]              char
1    [PTR_TYPE]          *
1    [WORD]              param2
1    [FPAREN_CLOSE]      )
1    [SEMICOLON]         ;
1    [NEWLINE]           
3    [TYPE]              void
3    [FUNC_PROTO]        foo2
3    [FPAREN_OPEN]       (
3    [TYPE]              int
3    [WORD]              param1
3    [COMMA]             ,
4    [TYPE]              int
4    [WORD]              param2
4    [COMMA]             ,
5    [TYPE]              char
5    [PTR_TYPE]          *
5    [WORD]              param2
5    [FPAREN_CLOSE]      )
5    [SEMICOLON]         ;
5    [NEWLINE]           
7    [TYPE]              void
7    [FUNC_PROTO]        foo3
7    [FPAREN_OPEN]       (
7    [TYPE]              int
7    [WORD]              param1
7    [COMMA]             ,
8    [TYPE]              int
8    [WORD]              param2
8    [COMMA]             ,
9    [TYPE]              char
9    [PTR_TYPE]          *
9    [WORD]              param2
10   [FPAREN_CLOSE]      )
10   [SEMICOLON]         ;
10   [NEWLINE]           
12   [STRUCT]            struct
12   [TYPE]              whoopee
12   [PTR_TYPE]          *
12   [FUNC_PROTO]        foo4
12   [FPAREN_OPEN]       (
12   [TYPE]              int
12   [WORD]              param1
12   [COMMA]             ,
12   [TYPE]              int
12   [WORD]              param2
12   [COMMA]             ,
12   [TYPE]              char
12   [PTR_TYPE]          *
12   [WORD]              param2
12   [FPAREN_CLOSE]      )
12   [SEMICOLON]         ;
12   [NEWLINE]           
14   [QUALIFIER]         const
14   [STRUCT]            struct
14   [TYPE]              snickers
14   [PTR_TYPE]          *
15   [FUNC_PROTO]        foo5
15   [FPAREN_OPEN]       (
15   [TYPE]              int
15   [WORD]              param1
15   [COMMA]             ,
15   [TYPE]              int
15   [WORD]              param2
15   [COMMA]             ,
15   [TYPE]              char
15   [PTR_TYPE]          *
15   [WORD]              param2
15   [FPAREN_CLOSE]      )
15   [SEMICOLON]         ;
15   [NEWLINE]           
18   [TYPE]              void
18   [FUNC_DEF]          foo
18   [FPAREN_OPEN]       (
18   [TYPE]              int
18   [WORD]              param1
18   [COMMA]             ,
18   [TYPE]              int
18   [WORD]              param2
18   [COMMA]             ,
18   [TYPE]              char
18   [PTR_TYPE]          *
18   [WORD]              param2
18   [FPAREN_CLOSE]      )
18   [NEWLINE]           
19   [BRACE_OPEN]        {
19   [NEWLINE]           
20   [FUNC_CALL]         printf
20   [FPAREN_OPEN]       (
20   [STRING]            "boo!\n"
20   [FPAREN_CLOSE]      )
20   [SEMICOLON]         ;
20   [NEWLINE]           
21   [BRACE_CLOSE]       }
21   [NEWLINE]           
23   [TYPE]              EXPORT
23   [TYPE]              int
23   [FUNC_PROTO]        DoStuff
23   [FPAREN_OPEN]       (
23   [TYPE]              int
23   [WORD]              Num
23   [FPAREN_CLOSE]      )
23   [SEMICOLON]         ;
23   [NEWLINE]           