Line [Token]             Text
1    [TYPE]              NSString
1    [PTR_TYPE]          *
1    [WORD]              str
1    [ASSIGN]            =
1    [PAREN_OPEN]        (
1    [WORD]              otherString
1    [QUESTION]          ?
1    [COND_COLON]        :
1    [STRING]            @"this is the placeholder"
1    [PAREN_CLOSE]       )
1    [SEMICOLON]         ;
1    [NEWLINE]           
2    [TYPE]              NSString
2    [PTR_TYPE]          *
2    [WORD]              str2
2    [ASSIGN]            =
2    [PAREN_OPEN]        (
2    [WORD]              str
2    [QUESTION]          ?
2    [WORD]              otherString
2    [COND_COLON]        :
2    [STRING]            @"this is the other placeholder"
2    [PAREN_CLOSE]       )
2    [SEMICOLON]         ;
2    [NEWLINE]           
3    [TYPE]              NSString
3    [PTR_TYPE]          *
3    [WORD]              str3
3    [ASSIGN]            =
3    [WORD]              str
3    [QUESTION]          ?
3    [SQUARE_OPEN]       [
3    [SQUARE_OPEN]       [
3    [OC_MSG_CLASS]      NSString
3    [OC_MSG_FUNC]       alloc
3    [SQUARE_CLOSE]      ]
3    [OC_MSG_FUNC]       initWithString
3    [OC_COLON]          :
3    [WORD]              str
3    [SQUARE_CLOSE]      ]
3    [COND_COLON]        :
3    [STRING]            @"this is the third placeholder"
3    [SEMICOLON]         ;
3    [NEWLINE]           
4    [TYPE]              id
4    [WORD]              str4
4    [ASSIGN]            =
4    [WORD]              str
4    [QUESTION]          ?
4    [SQUARE_OPEN]       [
4    [OC_MSG_CLASS]      self
4    [OC_MSG_FUNC]       methodWithParameter1
4    [OC_COLON]          :
4    [OC_AT]             @
4    [BRACE_OPEN]        {
4    [STRING]            @"bla"
4    [OC_DICT_COLON]     :
4    [PAREN_OPEN]        (
4    [BRACE_OPEN]        {
4    [SQUARE_OPEN]       [
4    [OC_MSG_CLASS]      self
4    [OC_MSG_FUNC]       anotherMethod
4    [OC_COLON]          :
4    [OC_AT]             @
4    [BRACE_OPEN]        {
4    [STRING]            @"id"
4    [OC_DICT_COLON]     :
4    [NUMBER]            @1
4    [BRACE_CLOSE]       }
4    [SQUARE_CLOSE]      ]
4    [SEMICOLON]         ;
4    [BRACE_CLOSE]       }
4    [PAREN_CLOSE]       )
4    [BRACE_CLOSE]       }
4    [NEWLINE]           
5    [OC_MSG_NAME]       andParameter2
5    [OC_COLON]          :
5    [OC_AT]             @
5    [BRACE_OPEN]        {
5    [STRING]            @"dict_key"
5    [OC_DICT_COLON]     :
5    [OC_AT]             @
5    [BRACE_OPEN]        {
5    [STRING]            @"nested_dict_key_1"
5    [OC_DICT_COLON]     :
5    [OC_AT]             @
5    [PAREN_OPEN]        (
5    [NUMBER]            1
5    [PAREN_CLOSE]       )
5    [COMMA]             ,
5    [STRING]            @"nested_dict_key_2"
5    [OC_DICT_COLON]     :
5    [STRING]            @"colon:in:string"
5    [BRACE_CLOSE]       }
5    [BRACE_CLOSE]       }
5    [SQUARE_CLOSE]      ]
5    [COND_COLON]        :
5    [SQUARE_OPEN]       [
5    [OC_MSG_CLASS]      self
5    [OC_MSG_FUNC]       anotherMethod
5    [OC_COLON]          :
5    [WORD]              str
5    [QUESTION]          ?
5    [NUMBER]            @1
5    [COND_COLON]        :
5    [NUMBER]            @2
5    [SQUARE_CLOSE]      ]
5    [SEMICOLON]         ;