Line [Token]             Text
1    [OC_INTF]           @interface
1    [OC_CLASS]          UCTestClass
1    [PAREN_OPEN]        (
1    [PAREN_CLOSE]       )
1    [NEWLINE]           
3    [OC_PROPERTY]       @property
3    [PAREN_OPEN]        (
3    [OC_PROPERTY_ATTR]    nonatomic
3    [COMMA]             ,
3    [OC_PROPERTY_ATTR]    readonly
3    [COMMA]             ,
3    [OC_PROPERTY_ATTR]    strong
3    [COMMA]             ,
3    [OC_PROPERTY_ATTR]    null_unspecified
3    [PAREN_CLOSE]       )
3    [TYPE]              NSString
3    [PTR_TYPE]          *
3    [WORD]              test1
3    [SEMICOLON]         ;
3    [NEWLINE]           
4    [OC_PROPERTY]       @property
4    [PAREN_OPEN]        (
4    [OC_PROPERTY_ATTR]    nonatomic
4    [COMMA]             ,
4    [OC_PROPERTY_ATTR]    readonly
4    [COMMA]             ,
4    [OC_PROPERTY_ATTR]    strong
4    [COMMA]             ,
4    [OC_PROPERTY_ATTR]    nullable
4    [PAREN_CLOSE]       )
4    [TYPE]              NSString
4    [PTR_TYPE]          *
4    [WORD]              test2
4    [SEMICOLON]         ;
4    [NEWLINE]           
5    [OC_PROPERTY]       @property
5    [PAREN_OPEN]        (
5    [OC_PROPERTY_ATTR]    nonatomic
5    [COMMA]             ,
5    [OC_PROPERTY_ATTR]    readonly
5    [COMMA]             ,
5    [OC_PROPERTY_ATTR]    strong
5    [COMMA]             ,
5    [OC_PROPERTY_ATTR]    nonnull
5    [COMMA]             ,
5    [OC_PROPERTY_ATTR]    getter
5    [ASSIGN]            =
5    [OC_SEL_NAME]       test2Getter
5    [PAREN_CLOSE]       )
5    [TYPE]              NSString
5    [PTR_TYPE]          *
5    [WORD]              test3
5    [SEMICOLON]         ;
5    [NEWLINE]           
6    [OC_PROPERTY]       @property
6    [PAREN_OPEN]        (
6    [OC_PROPERTY_ATTR]    nonatomic
6    [COMMA]             ,
6    [OC_PROPERTY_ATTR]    readonly
6    [COMMA]             ,
6    [OC_PROPERTY_ATTR]    strong
6    [COMMA]             ,
6    [OC_PROPERTY_ATTR]    null_resettable
6    [COMMA]             ,
6    [OC_PROPERTY_ATTR]    getter
6    [ASSIGN]            =
6    [OC_SEL_NAME]       test2Getter
6    [COMMA]             ,
6    [OC_PROPERTY_ATTR]    setter
6    [ASSIGN]            =
6    [OC_SEL_NAME]       test2Setter
6    [OC_SEL_NAME]       :
6    [PAREN_CLOSE]       )
6    [TYPE]              NSString
6    [PTR_TYPE]          *
6    [WORD]              test4
6    [SEMICOLON]         ;
6    [NEWLINE]           
8    [OC_END]            @end
8    [NEWLINE]           