Line [Parent]            Text
1    [NONE]              typedef
1    [NONE]              HRESULT
1    [NONE]              (
1    [NONE]              WINAPI
1    [NONE]              *
1    [TYPEDEF]           Foo
1    [NONE]              )
1    [FUNC_CALL]         (
1    [NONE]              const
1    [NONE]              void
1    [NONE]              *
1    [NONE]              pData
1    [NONE]              ,
1    [NONE]              SIZE_T
1    [NONE]              size
1    [NONE]              ,
1    [NONE]              UINT
1    [NONE]              flags
1    [NONE]              ,
1    [NONE]              const
1    [NONE]              char
1    [NONE]              *
1    [NONE]              szStr
1    [NONE]              ,
1    [NONE]              D3D10BlobHack
1    [NONE]              *
1    [NONE]              *
1    [NONE]              ppBlob
1    [FUNC_CALL]         )
1    [TYPEDEF]           ;
1    [NONE]              