Line [Parent]            Text
1    [NONE]              CGPathMoveToPoint
1    [FUNC_CALL]         (
1    [NONE]              bottomArrow
1    [NONE]              ,
1    [NONE]              NULL
1    [NONE]              ,
1    [NONE]              round
1    [FUNC_CALL]         (
1    [NONE]              aPoint
1    [NONE]              .
1    [NONE]              x
1    [FUNC_CALL]         )
1    [NONE]              +
1    [NONE]              .5
1    [NONE]              /
1    [NONE]              self
1    [NONE]              .
1    [NONE]              contentsScale
1    [NONE]              -
1    [NONE]              3
1    [NONE]              ,
1    [NONE]              aPoint
1    [NONE]              .
1    [NONE]              y
1    [NONE]              -
1    [NONE]              aLength
1    [NONE]              +
1    [NONE]              1
1    [NONE]              +
1    [NONE]              4
1    [FUNC_CALL]         )
1    [NONE]              ;
1    [NONE]              
2    [NONE]              CGPathAddLineToPoint
2    [FUNC_CALL]         (
2    [NONE]              bottomArrow
2    [NONE]              ,
2    [NONE]              NULL
2    [NONE]              ,
2    [NONE]              round
2    [FUNC_CALL]         (
2    [NONE]              aPoint
2    [NONE]              .
2    [NONE]              x
2    [FUNC_CALL]         )
2    [NONE]              +
2    [NONE]              .5
2    [NONE]              /
2    [NONE]              self
2    [NONE]              .
2    [NONE]              contentsScale
2    [NONE]              ,
2    [NONE]              aPoint
2    [NONE]              .
2    [NONE]              y
2    [NONE]              -
2    [NONE]              aLength
2    [NONE]              +
2    [NONE]              1
2    [FUNC_CALL]         )
2    [NONE]              ;
2    [NONE]              
3    [NONE]              CGPathAddLineToPoint
3    [FUNC_CALL]         (
3    [NONE]              bottomArrow
3    [NONE]              ,
3    [NONE]              NULL
3    [NONE]              ,
3    [NONE]              round
3    [FUNC_CALL]         (
3    [NONE]              aPoint
3    [NONE]              .
3    [NONE]              x
3    [FUNC_CALL]         )
3    [NONE]              +
3    [NONE]              .5
3    [NONE]              /
3    [NONE]              self
3    [NONE]              .
3    [NONE]              contentsScale
3    [NONE]              +
3    [NONE]              3
3    [NONE]              ,
3    [NONE]              aPoint
3    [NONE]              .
3    [NONE]              y
3    [NONE]              -
3    [NONE]              aLength
3    [NONE]              +
3    [NONE]              1
3    [NONE]              +
3    [NONE]              4
3    [FUNC_CALL]         )
3    [NONE]              ;
3    [NONE]              