Line [Parent]            Text
1    [PP_DEFINE]         #
1    [NONE]              define
1    [NONE]              FOO
1    [MACRO_FUNC]        (
1    [NONE]              X
1    [MACRO_FUNC]        )
1    [NONE]              \
2    [NONE]              template
2    [TEMPLATE]          <
2    [NONE]              unsigned
2    [NONE]              _blk_sz
2    [NONE]              ,
2    [NONE]              typename
2    [NONE]              _run_type
2    [NONE]              ,
2    [NONE]              class
2    [NONE]              __pos_type
2    [TEMPLATE]          >
2    [NONE]              \
3    [NONE]              inline
3    [NONE]              X
3    [TEMPLATE]          <
3    [NONE]              _blk_sz
3    [NONE]              ,
3    [NONE]              _run_type
3    [NONE]              ,
3    [NONE]              __pos_type
3    [TEMPLATE]          >
3    [FUNC_DEF]          operator
3    [OPERATOR]          -
3    [FUNC_DEF]          (
3    [NONE]              \
4    [NONE]              const
4    [NONE]              X
4    [TEMPLATE]          <
4    [NONE]              _blk_sz
4    [NONE]              ,
4    [NONE]              _run_type
4    [NONE]              ,
4    [NONE]              __pos_type
4    [TEMPLATE]          >
4    [NONE]              &
4    [NONE]              a
4    [NONE]              ,
4    [NONE]              \
5    [NONE]              typename
5    [NONE]              X
5    [TEMPLATE]          <
5    [NONE]              _blk_sz
5    [NONE]              ,
5    [NONE]              _run_type
5    [NONE]              ,
5    [NONE]              __pos_type
5    [TEMPLATE]          >
5    [NONE]              ::
5    [NONE]              _pos_type
5    [NONE]              off
5    [FUNC_DEF]          )
5    [NONE]              \
6    [FUNC_DEF]          {
6    [NONE]              \
7    [NONE]              return
7    [NONE]              X
7    [TEMPLATE]          <
7    [NONE]              _blk_sz
7    [NONE]              ,
7    [NONE]              _run_type
7    [NONE]              ,
7    [NONE]              __pos_type
7    [TEMPLATE]          >
7    [FUNC_CALL]         (
7    [NONE]              a
7    [NONE]              .
7    [NONE]              array
7    [NONE]              ,
7    [NONE]              a
7    [NONE]              .
7    [NONE]              pos
7    [NONE]              -
7    [NONE]              off
7    [FUNC_CALL]         )
7    [NONE]              ;
7    [NONE]              \
8    [FUNC_DEF]          }
8    [NONE]              \
9    [NONE]              template
9    [TEMPLATE]          <
9    [NONE]              unsigned
9    [NONE]              _blk_sz
9    [NONE]              ,
9    [NONE]              typename
9    [NONE]              _run_type
9    [NONE]              ,
9    [NONE]              class
9    [NONE]              __pos_type
9    [TEMPLATE]          >
9    [NONE]              \
10   [NONE]              inline
10   [NONE]              X
10   [TEMPLATE]          <
10   [NONE]              _blk_sz
10   [NONE]              ,
10   [NONE]              _run_type
10   [NONE]              ,
10   [NONE]              __pos_type
10   [TEMPLATE]          >
10   [NONE]              &
10   [FUNC_DEF]          operator
10   [OPERATOR]          -=
10   [FUNC_DEF]          (
10   [NONE]              \
11   [NONE]              X
11   [TEMPLATE]          <
11   [NONE]              _blk_sz
11   [NONE]              ,
11   [NONE]              _run_type
11   [NONE]              ,
11   [NONE]              __pos_type
11   [TEMPLATE]          >
11   [NONE]              &
11   [NONE]              a
11   [NONE]              ,
11   [NONE]              \
12   [NONE]              typename
12   [NONE]              X
12   [TEMPLATE]          <
12   [NONE]              _blk_sz
12   [NONE]              ,
12   [NONE]              _run_type
12   [NONE]              ,
12   [NONE]              __pos_type
12   [TEMPLATE]          >
12   [NONE]              ::
12   [NONE]              _pos_type
12   [NONE]              off
12   [FUNC_DEF]          )
12   [NONE]              \
13   [FUNC_DEF]          {
13   [NONE]              \
14   [NONE]              a
14   [NONE]              .
14   [NONE]              pos
14   [NONE]              -=
14   [NONE]              off
14   [NONE]              ;
14   [NONE]              \
15   [NONE]              return
15   [NONE]              a
15   [NONE]              ;
15   [NONE]              \
16   [FUNC_DEF]          }
16   [NONE]              