Line [Parent]            Text
1    [NONE]              typename
1    [FUNC_DEF]          std
1    [FUNC_DEF]          ::
1    [FUNC_DEF]          enable_if
1    [TEMPLATE]          <
1    [NONE]              !
1    [NONE]              std
1    [NONE]              ::
1    [NONE]              is_void
1    [TEMPLATE]          <
1    [NONE]              T
1    [TEMPLATE]          >
1    [NONE]              ::
1    [NONE]              value
1    [NONE]              ,
1    [NONE]              QVector
1    [TEMPLATE]          <
1    [NONE]              T
1    [TEMPLATE]          >
1    [TEMPLATE]          >
1    [FUNC_DEF]          ::
1    [FUNC_DEF]          type
1    [NONE]              dummy
1    [FUNC_DEF]          (
1    [NONE]              const
1    [NONE]              std
1    [NONE]              ::
1    [NONE]              function
1    [TEMPLATE]          <
1    [NONE]              T
1    [NONE]              *
1    [C_CAST]            (
1    [C_CAST]            const
1    [C_CAST]            S
1    [C_CAST]            &
1    [C_CAST]            )
1    [TEMPLATE]          >
1    [NONE]              &
1    [NONE]              pFunc
1    [NONE]              ,
1    [NONE]              const
1    [NONE]              QVector
1    [TEMPLATE]          <
1    [NONE]              S
1    [TEMPLATE]          >
1    [NONE]              &
1    [NONE]              pItems
1    [FUNC_DEF]          )
1    [NONE]              
2    [FUNC_DEF]          {
2    [NONE]              
3    [NONE]              return
3    [NONE]              QVector
3    [TEMPLATE]          <
3    [NONE]              T
3    [TEMPLATE]          >
3    [FUNC_CALL]         (
3    [FUNC_CALL]         )
3    [NONE]              ;
3    [NONE]              
4    [FUNC_DEF]          }
4    [NONE]              
7    [NONE]              typename
7    [FUNC_DEF]          std
7    [FUNC_DEF]          ::
7    [FUNC_DEF]          enable_if
7    [TEMPLATE]          <
7    [NONE]              !
7    [NONE]              std
7    [NONE]              ::
7    [NONE]              is_void
7    [TEMPLATE]          <
7    [NONE]              T
7    [TEMPLATE]          >
7    [NONE]              ::
7    [NONE]              value
7    [NONE]              ,
7    [NONE]              QVector
7    [TEMPLATE]          <
7    [NONE]              T
7    [TEMPLATE]          >
7    [TEMPLATE]          >
7    [FUNC_DEF]          ::
7    [FUNC_DEF]          type
7    [NONE]              filter
7    [FUNC_DEF]          (
7    [NONE]              const
7    [NONE]              std
7    [NONE]              ::
7    [NONE]              function
7    [TEMPLATE]          <
7    [NONE]              bool
7    [CPP_CAST]          (
7    [NONE]              const
7    [NONE]              T
7    [NONE]              &
7    [CPP_CAST]          )
7    [TEMPLATE]          >
7    [NONE]              &
7    [NONE]              pFunc
7    [NONE]              ,
7    [NONE]              const
7    [NONE]              QVector
7    [TEMPLATE]          <
7    [NONE]              T
7    [TEMPLATE]          >
7    [NONE]              &
7    [NONE]              pItems
7    [FUNC_DEF]          )
7    [NONE]              
8    [FUNC_DEF]          {
8    [NONE]              
9    [NONE]              return
9    [NONE]              QVector
9    [TEMPLATE]          <
9    [NONE]              T
9    [TEMPLATE]          >
9    [FUNC_CALL]         (
9    [FUNC_CALL]         )
9    [NONE]              ;
9    [NONE]              
10   [FUNC_DEF]          }
10   [NONE]              