Line [Parent]            Text
1    [NONE]              template
1    [TEMPLATE]          <
1    [NONE]              class
1    [NONE]              CLASS_PARAMETER_0
1    [NONE]              ,
1    [NONE]              class
1    [NONE]              CLASS_PARAMETER_1
1    [NONE]              ,
1    [NONE]              class
1    [NONE]              CLASS_PARAMETER_2
1    [NONE]              ,
1    [NONE]              class
1    [NONE]              CLASS_PARAMETER_3
1    [NONE]              ,
1    [NONE]              class
1    [NONE]              CLASS_PARAMETER_4
1    [NONE]              ,
1    [NONE]              
1    [NONE]              class
1    [NONE]              CLASS_PARAMETER_5
1    [TEMPLATE]          >
1    [NONE]              
2    [TEMPLATE]          class
2    [CLASS]             MyTemplateClass
2    [NONE]              
3    [CLASS]             {
3    [NONE]              
4    [NONE]              public
4    [NONE]              :
4    [NONE]              
5    [FUNC_PROTO]        MyTemplateClass
5    [TEMPLATE]          <
5    [NONE]              my
5    [NONE]              ::
5    [NONE]              super
5    [NONE]              ::
5    [NONE]              cool
5    [NONE]              ::
5    [NONE]              _and
5    [NONE]              ::
5    [NONE]              fancy
5    [NONE]              ::
5    [NONE]              type
5    [NONE]              ,
5    [NONE]              my
5    [NONE]              ::
5    [NONE]              super
5    [NONE]              ::
5    [NONE]              cool
5    [NONE]              ::
5    [NONE]              _and
5    [NONE]              ::
5    [NONE]              fancy
5    [NONE]              ::
5    [NONE]              type
5    [NONE]              ,
5    [NONE]              my
5    [NONE]              ::
5    [NONE]              super
5    [NONE]              ::
5    [NONE]              cool
5    [NONE]              ::
5    [NONE]              _and
5    [NONE]              ::
5    [NONE]              fancy
5    [NONE]              ::
5    [NONE]              type
5    [NONE]              ,
5    [NONE]              
5    [NONE]              my
5    [NONE]              ::
5    [NONE]              super
5    [NONE]              ::
5    [NONE]              cool
5    [NONE]              ::
5    [NONE]              _and
5    [NONE]              ::
5    [NONE]              fancy
5    [NONE]              ::
5    [NONE]              type
5    [NONE]              ,
5    [NONE]              my
5    [NONE]              ::
5    [NONE]              super
5    [NONE]              ::
5    [NONE]              cool
5    [NONE]              ::
5    [NONE]              _and
5    [NONE]              ::
5    [NONE]              fancy
5    [NONE]              ::
5    [NONE]              type
5    [NONE]              ,
5    [NONE]              my
5    [NONE]              ::
5    [NONE]              super
5    [NONE]              ::
5    [NONE]              cool
5    [NONE]              ::
5    [NONE]              _and
5    [NONE]              ::
5    [NONE]              fancy
5    [NONE]              ::
5    [NONE]              type
5    [TEMPLATE]          >
5    [NONE]              foo
5    [FUNC_PROTO]        (
5    [FUNC_PROTO]        )
5    [FUNC_PROTO]        ;
5    [NONE]              
6    [CLASS]             }
6    [CLASS]             ;
6    [NONE]              