Line [Parent]            Text
1    [NONE]              WRAP_FUNCTION
1    [FUNC_CALL]         (
1    [NONE]              Foo
1    [NONE]              ,
1    [NONE]              Bar
1    [NONE]              &
1    [NONE]              (
1    [NONE]              void
1    [NONE]              )
1    [FUNC_CALL]         )
1    [NONE]              ;
1    [NONE]              
2    [NONE]              WRAP_FUNCTION
2    [FUNC_CALL]         (
2    [NONE]              Foo
2    [NONE]              ,
2    [NONE]              Bar
2    [NONE]              *
2    [NONE]              (
2    [NONE]              void
2    [NONE]              )
2    [FUNC_CALL]         )
2    [NONE]              ;
2    [NONE]              
3    [NONE]              WRAP_FUNCTION
3    [FUNC_CALL]         (
3    [NONE]              Foo
3    [NONE]              ,
3    [NONE]              (
3    [NONE]              Bar
3    [NONE]              &
3    [NONE]              (
3    [NONE]              void
3    [NONE]              )
3    [NONE]              )
3    [FUNC_CALL]         )
3    [NONE]              ;
3    [NONE]              
4    [NONE]              WRAP_FUNCTION
4    [FUNC_CALL]         (
4    [NONE]              Foo
4    [NONE]              ,
4    [NONE]              (
4    [NONE]              Bar
4    [NONE]              *
4    [NONE]              (
4    [NONE]              void
4    [NONE]              )
4    [NONE]              )
4    [FUNC_CALL]         )
4    [NONE]              ;
4    [NONE]              