Line [Parent]            Text
1    [FUNC_DEF]          void
1    [FUNC_DEF]          Foo
1    [FUNC_DEF]          ::
1    [NONE]              doo
1    [FUNC_DEF]          (
1    [FUNC_DEF]          )
1    [NONE]              
2    [FUNC_DEF]          {
2    [NONE]              
3    [NONE]              m_stackCache
3    [NONE]              [
3    [NONE]              m_currentStackNr
3    [NONE]              ]
3    [NONE]              ->
3    [NONE]              operator
3    [OPERATOR]          []
3    [FUNC_CALL]         (
3    [NONE]              0
3    [FUNC_CALL]         )
3    [NONE]              =
3    [NONE]              new
3    [NONE]              QStandardItem
3    [FUNC_CALL]         (
3    [NONE]              QString
3    [NONE]              ::
3    [NONE]              number
3    [FUNC_CALL]         (
3    [NONE]              m_currentStackNr
3    [FUNC_CALL]         )
3    [FUNC_CALL]         )
3    [NONE]              ;
3    [NONE]              
4    [NONE]              m_stackCache
4    [NONE]              [
4    [NONE]              m_currentStackNr
4    [NONE]              ]
4    [NONE]              ->
4    [NONE]              operator
4    [OPERATOR]          []
4    [FUNC_CALL]         (
4    [NONE]              1
4    [FUNC_CALL]         )
4    [NONE]              =
4    [NONE]              new
4    [NONE]              QStandardItem
4    [FUNC_CALL]         (
4    [NONE]              tr
4    [FUNC_CALL]         (
4    [NONE]              "OK"
4    [FUNC_CALL]         )
4    [FUNC_CALL]         )
4    [NONE]              ;
4    [NONE]              
5    [NONE]              m_stackCache
5    [NONE]              [
5    [NONE]              m_currentStackNr
5    [NONE]              ]
5    [NONE]              ->
5    [NONE]              operator
5    [OPERATOR]          []
5    [FUNC_CALL]         (
5    [NONE]              2
5    [FUNC_CALL]         )
5    [NONE]              =
5    [NONE]              new
5    [NONE]              QStandardItem
5    [FUNC_CALL]         (
5    [NONE]              "0"
5    [FUNC_CALL]         )
5    [NONE]              ;
5    [NONE]              
6    [NONE]              m_stackCache
6    [NONE]              [
6    [NONE]              m_currentStackNr
6    [NONE]              ]
6    [NONE]              ->
6    [NONE]              operator
6    [OPERATOR]          []
6    [FUNC_CALL]         (
6    [NONE]              3
6    [FUNC_CALL]         )
6    [NONE]              =
6    [NONE]              new
6    [NONE]              QStandardItem
6    [FUNC_CALL]         (
6    [NONE]              "0"
6    [FUNC_CALL]         )
6    [NONE]              ;
6    [NONE]              
7    [NONE]              m_stackCache
7    [NONE]              [
7    [NONE]              m_currentStackNr
7    [NONE]              ]
7    [NONE]              ->
7    [NONE]              operator
7    [OPERATOR]          []
7    [FUNC_CALL]         (
7    [NONE]              4
7    [FUNC_CALL]         )
7    [NONE]              =
7    [NONE]              new
7    [NONE]              QStandardItem
7    [FUNC_CALL]         (
7    [FUNC_CALL]         )
7    [NONE]              ;
7    [NONE]              
8    [FUNC_DEF]          }
8    [NONE]              