Line [Parent]            Text
1    [NONE]              Foo
1    [NONE]              *
1    [NONE]              foo
1    [NONE]              =
1    [NONE]              new
1    [NONE]              Foo
1    [FUNC_CALL]         (
1    [NONE]              a
1    [NONE]              ,
1    [NONE]              v
1    [FUNC_CALL]         )
1    [NONE]              ;
1    [NONE]              
3    [NONE]              Foo
3    [NONE]              *
3    [NONE]              foo
3    [NONE]              =
3    [NONE]              new
3    [NEW]               (
3    [NONE]              ptr
3    [NONE]              ,
3    [NONE]              std
3    [NONE]              ::
3    [NONE]              nothrow
3    [NEW]               )
3    [NONE]              Foo
3    [NONE]              []
3    [NONE]              ;
3    [NONE]              
4    [NONE]              Foo
4    [NONE]              *
4    [NONE]              foo
4    [NONE]              =
4    [NONE]              new
4    [NEW]               (
4    [NONE]              ptr
4    [NEW]               )
4    [NONE]              Foo
4    [FUNC_CALL]         (
4    [FUNC_CALL]         )
4    [NONE]              ;
4    [NONE]              
5    [NONE]              Foo
5    [NONE]              *
5    [NONE]              foo
5    [NONE]              =
5    [NONE]              new
5    [NEW]               (
5    [NONE]              FOO
5    [FUNC_CALL]         (
5    [NONE]              ptr
5    [FUNC_CALL]         )
5    [NEW]               )
5    [NONE]              Foo
5    [FUNC_CALL]         (
5    [FUNC_CALL]         )
5    [NONE]              ;
5    [NONE]              
7    [NONE]              Foo
7    [NONE]              *
7    [NONE]              foo
7    [NONE]              =
7    [NONE]              new
7    [NEW]               (
7    [NONE]              ptr
7    [NONE]              ,
7    [NONE]              std
7    [NONE]              ::
7    [NONE]              nothrow
7    [NEW]               )
7    [NONE]              Foo
7    [NONE]              []
7    [NONE]              ;
7    [NONE]              
8    [NONE]              Foo
8    [NONE]              *
8    [NONE]              foo
8    [NONE]              =
8    [NONE]              new
8    [NEW]               (
8    [NONE]              ptr
8    [NEW]               )
8    [NONE]              Foo
8    [FUNC_CALL]         (
8    [FUNC_CALL]         )
8    [NONE]              ;
8    [NONE]              
9    [NONE]              Foo
9    [NONE]              *
9    [NONE]              foo
9    [NONE]              =
9    [NONE]              new
9    [NEW]               (
9    [NONE]              FOO
9    [FUNC_CALL]         (
9    [NONE]              ptr
9    [FUNC_CALL]         )
9    [NEW]               )
9    [NONE]              Foo
9    [FUNC_CALL]         (
9    [FUNC_CALL]         )
9    [NONE]              ;
9    [NONE]              