Line [Parent]            Text
1    [NONE]              ::
1    [NONE]              some
1    [NONE]              ::
1    [NONE]              very
1    [NONE]              ::
1    [NONE]              looong
1    [NONE]              ::
1    [NONE]              _and
1    [NONE]              ::
1    [NONE]              complicated
1    [NONE]              ::
1    [NONE]              name
1    [NONE]              ::
1    [NONE]              MyType
1    [NONE]              &
1    [NONE]              a
1    [NONE]              ;