Line [Parent]            Text
1    [NONE]              friend
1    [FUNC_PROTO]        void
1    [FUNC_START]        ::
1    [FUNC_PROTO]        test
1    [FUNC_PROTO]        ::
1    [NONE]              swap
1    [TEMPLATE]          <
1    [TEMPLATE]          >
1    [FUNC_PROTO]        (
1    [NONE]              future
1    [TEMPLATE]          <
1    [NONE]              T
1    [TEMPLATE]          >
1    [NONE]              &
1    [NONE]              ,
1    [NONE]              future
1    [TEMPLATE]          <
1    [NONE]              T
1    [TEMPLATE]          >
1    [NONE]              &
1    [FUNC_PROTO]        )
1    [FUNC_PROTO]        ;
1    [NONE]              