Line [Parent]            Text
1    [NONE]              var
1    [NONE]              dude
1    [NONE]              =
1    [NONE]              "Dude"
1    [NONE]              ;
1    [NONE]              
2    [NONE]              var
2    [NONE]              dude2
2    [NONE]              =
2    [NONE]              new
2    [NEW]               {
2    [NONE]              Name
2    [NONE]              =
2    [NONE]              "Dude"
2    [NONE]              ,
2    [NONE]              Age
2    [NONE]              =
2    [NONE]              30
2    [NONE]              ,
2    [NEW]               }
2    [NONE]              ;
2    [NONE]              
3    [NONE]              var
3    [NONE]              dude3
3    [NONE]              =
3    [NONE]              new
3    [NEW]               {
3    [NONE]              Name
3    [NONE]              =
3    [NONE]              "Dude"
3    [NONE]              ,
3    [NONE]              Age
3    [NONE]              =
3    [NONE]              30
3    [NONE]              ,
3    [NONE]              Kids
3    [NONE]              =
3    [NONE]              new
3    [NEW]               {
3    [NONE]              Name
3    [NONE]              =
3    [NONE]              "LittleDude"
3    [NEW]               }
3    [NEW]               }
3    [NONE]              ;
3    [NONE]              
4    [NONE]              var
4    [NONE]              dude4
4    [NONE]              =
4    [NONE]              new
4    [NEW]               {
4    [NONE]              Name
4    [NONE]              =
4    [NONE]              "Dude"
4    [NONE]              ,
4    [NONE]              Age
4    [NONE]              =
4    [NONE]              30
4    [NONE]              ,
4    [NONE]              Kids
4    [NONE]              =
4    [NONE]              new
4    [NEW]               []
4    [NEW]               {
4    [NONE]              "LittleDude"
4    [NEW]               }
4    [NEW]               }
4    [NONE]              ;
4    [NONE]              
5    [NONE]              var
5    [NONE]              dude5
5    [NONE]              =
5    [NONE]              new
5    [NEW]               {
5    [NONE]              Name
5    [NONE]              =
5    [NONE]              "Dude"
5    [NONE]              ,
5    [NONE]              Age
5    [NONE]              =
5    [NONE]              30
5    [NONE]              ,
5    [NONE]              Kids
5    [NONE]              =
5    [NONE]              new
5    [NEW]               []
5    [NEW]               {
5    [NONE]              new
5    [NEW]               {
5    [NONE]              Name
5    [NONE]              =
5    [NONE]              "LittleDude"
5    [NEW]               }
5    [NEW]               }
5    [NEW]               }
5    [NONE]              ;
5    [NONE]              
6    [NONE]              Action
6    [NONE]              y
6    [NONE]              =
6    [NONE]              (
6    [NONE]              )
6    [NONE]              =>
6    [LAMBDA]            {
6    [LAMBDA]            }
6    [NONE]              ;
6    [NONE]              
7    [NONE]              Func
7    [TEMPLATE]          <
7    [NONE]              int
7    [NONE]              ,
7    [NONE]              float
7    [NONE]              ,
7    [NONE]              bool
7    [TEMPLATE]          >
7    [NONE]              z
7    [NONE]              =
7    [NONE]              (
7    [NONE]              a
7    [NONE]              ,
7    [NONE]              b
7    [NONE]              )
7    [NONE]              =>
7    [LAMBDA]            {
7    [NONE]              var
7    [NONE]              z
7    [NONE]              =
7    [NONE]              new
7    [NEW]               {
7    [NONE]              a
7    [NONE]              ,
7    [NONE]              b
7    [NEW]               }
7    [NONE]              ;
7    [NONE]              return
7    [NONE]              z
7    [NONE]              ==
7    [NONE]              null
7    [NONE]              ;
7    [LAMBDA]            }
7    [NONE]              ;
7    [NONE]              