Line [Parent]            Text
1    [FUNC_PROTO]        static
1    [FUNC_PROTO]        void
1    [NONE]              WriteArrayToDrag
1    [FUNC_PROTO]        (
1    [NONE]              NSArray
1    [NONE]              *
1    [NONE]              array
1    [NONE]              ,
1    [NONE]              NSPasteboard
1    [NONE]              *
1    [NONE]              pboard
1    [NONE]              ,
1    [NONE]              NSString
1    [NONE]              *
1    [NONE]              pboardType
1    [FUNC_PROTO]        )
1    [FUNC_PROTO]        ;
1    [NONE]              
2    [FUNC_PROTO]        static
2    [FUNC_PROTO]        OSStatus
2    [NONE]              FindProcess
2    [FUNC_PROTO]        (
2    [NONE]              const
2    [NONE]              FSRef
2    [NONE]              *
2    [NONE]              appRef
2    [NONE]              ,
2    [NONE]              ProcessSerialNumber
2    [NONE]              *
2    [NONE]              pPSN
2    [NONE]              ,
2    [NONE]              NSString
2    [NONE]              *
2    [NONE]              application
2    [NONE]              ,
2    [NONE]              bool
2    [NONE]              permissiveSearching
2    [FUNC_PROTO]        )
2    [FUNC_PROTO]        ;
2    [NONE]              
3    [FUNC_PROTO]        NSString
3    [FUNC_PROTO]        *
3    [NONE]              MakeNSString
3    [FUNC_PROTO]        (
3    [NONE]              const
3    [NONE]              std
3    [NONE]              ::
3    [NONE]              string
3    [NONE]              &
3    [NONE]              string
3    [FUNC_PROTO]        )
3    [FUNC_PROTO]        ;
3    [NONE]              