Line [Token]             Text
1    [TYPEDEF]           typedef
1    [TYPE]              HRESULT
1    [PAREN_OPEN]        (
1    [WORD]              WINAPI
1    [PTR_TYPE]          *
1    [WORD]              Foo
1    [PAREN_CLOSE]       )
1    [FPAREN_OPEN]       (
1    [QUALIFIER]         const
1    [TYPE]              void
1    [PTR_TYPE]          *
1    [WORD]              pData
1    [COMMA]             ,
1    [TYPE]              SIZE_T
1    [WORD]              size
1    [COMMA]             ,
1    [TYPE]              UINT
1    [WORD]              flags
1    [COMMA]             ,
1    [QUALIFIER]         const
1    [TYPE]              char
1    [PTR_TYPE]          *
1    [WORD]              szStr
1    [COMMA]             ,
1    [TYPE]              D3D10BlobHack
1    [PTR_TYPE]          *
1    [PTR_TYPE]          *
1    [WORD]              ppBlob
1    [FPAREN_CLOSE]      )
1    [SEMICOLON]         ;
1    [NEWLINE]           