Line [Token]             Text
1    [PREPROC]           #
1    [PP_DEFINE]         define
1    [MACRO_FUNC]        FOO
1    [FPAREN_OPEN]       (
1    [WORD]              X
1    [FPAREN_CLOSE]      )
1    [NL_CONT]           \
2    [TEMPLATE]          template
2    [ANGLE_OPEN]        <
2    [TYPE]              unsigned
2    [TYPE]              _blk_sz
2    [COMMA]             ,
2    [TYPENAME]          typename
2    [TYPE]              _run_type
2    [COMMA]             ,
2    [TYPE]              class
2    [TYPE]              __pos_type
2    [ANGLE_CLOSE]       >
2    [NL_CONT]           \
3    [QUALIFIER]         inline
3    [TYPE]              X
3    [ANGLE_OPEN]        <
3    [TYPE]              _blk_sz
3    [COMMA]             ,
3    [TYPE]              _run_type
3    [COMMA]             ,
3    [TYPE]              __pos_type
3    [ANGLE_CLOSE]       >
3    [OPERATOR]          operator
3    [FUNC_DEF]          -
3    [FPAREN_OPEN]       (
3    [NL_CONT]           \
4    [QUALIFIER]         const
4    [TYPE]              X
4    [ANGLE_OPEN]        <
4    [TYPE]              _blk_sz
4    [COMMA]             ,
4    [TYPE]              _run_type
4    [COMMA]             ,
4    [TYPE]              __pos_type
4    [ANGLE_CLOSE]       >
4    [BYREF]             &
4    [WORD]              a
4    [COMMA]             ,
4    [NL_CONT]           \
5    [TYPENAME]          typename
5    [TYPE]              X
5    [ANGLE_OPEN]        <
5    [TYPE]              _blk_sz
5    [COMMA]             ,
5    [TYPE]              _run_type
5    [COMMA]             ,
5    [TYPE]              __pos_type
5    [ANGLE_CLOSE]       >
5    [DC_MEMBER]         ::
5    [TYPE]              _pos_type
5    [WORD]              off
5    [FPAREN_CLOSE]      )
5    [NL_CONT]           \
6    [BRACE_OPEN]        {
6    [NL_CONT]           \
7    [RETURN]            return
7    [FUNC_CALL]         X
7    [ANGLE_OPEN]        <
7    [TYPE]              _blk_sz
7    [COMMA]             ,
7    [TYPE]              _run_type
7    [COMMA]             ,
7    [TYPE]              __pos_type
7    [ANGLE_CLOSE]       >
7    [FPAREN_OPEN]       (
7    [WORD]              a
7    [MEMBER]            .
7    [WORD]              array
7    [COMMA]             ,
7    [WORD]              a
7    [MEMBER]            .
7    [WORD]              pos
7    [ARITH]             -
7    [WORD]              off
7    [FPAREN_CLOSE]      )
7    [SEMICOLON]         ;
7    [NL_CONT]           \
8    [BRACE_CLOSE]       }
8    [NL_CONT]           \
9    [TEMPLATE]          template
9    [ANGLE_OPEN]        <
9    [TYPE]              unsigned
9    [TYPE]              _blk_sz
9    [COMMA]             ,
9    [TYPENAME]          typename
9    [TYPE]              _run_type
9    [COMMA]             ,
9    [TYPE]              class
9    [TYPE]              __pos_type
9    [ANGLE_CLOSE]       >
9    [NL_CONT]           \
10   [QUALIFIER]         inline
10   [TYPE]              X
10   [ANGLE_OPEN]        <
10   [TYPE]              _blk_sz
10   [COMMA]             ,
10   [TYPE]              _run_type
10   [COMMA]             ,
10   [TYPE]              __pos_type
10   [ANGLE_CLOSE]       >
10   [BYREF]             &
10   [OPERATOR]          operator
10   [FUNC_DEF]          -=
10   [FPAREN_OPEN]       (
10   [NL_CONT]           \
11   [TYPE]              X
11   [ANGLE_OPEN]        <
11   [TYPE]              _blk_sz
11   [COMMA]             ,
11   [TYPE]              _run_type
11   [COMMA]             ,
11   [TYPE]              __pos_type
11   [ANGLE_CLOSE]       >
11   [BYREF]             &
11   [WORD]              a
11   [COMMA]             ,
11   [NL_CONT]           \
12   [TYPENAME]          typename
12   [TYPE]              X
12   [ANGLE_OPEN]        <
12   [TYPE]              _blk_sz
12   [COMMA]             ,
12   [TYPE]              _run_type
12   [COMMA]             ,
12   [TYPE]              __pos_type
12   [ANGLE_CLOSE]       >
12   [DC_MEMBER]         ::
12   [TYPE]              _pos_type
12   [WORD]              off
12   [FPAREN_CLOSE]      )
12   [NL_CONT]           \
13   [BRACE_OPEN]        {
13   [NL_CONT]           \
14   [TYPE]              a
14   [MEMBER]            .
14   [WORD]              pos
14   [ASSIGN]            -=
14   [WORD]              off
14   [SEMICOLON]         ;
14   [NL_CONT]           \
15   [RETURN]            return
15   [WORD]              a
15   [SEMICOLON]         ;
15   [NL_CONT]           \
16   [BRACE_CLOSE]       }
16   [NEWLINE]           