Line [Token]             Text
1    [TEMPLATE]          template
1    [ANGLE_OPEN]        <
1    [TYPE]              class
1    [TYPE]              CLASS_PARAMETER_0
1    [COMMA]             ,
1    [TYPE]              class
1    [TYPE]              CLASS_PARAMETER_1
1    [COMMA]             ,
1    [TYPE]              class
1    [TYPE]              CLASS_PARAMETER_2
1    [COMMA]             ,
1    [TYPE]              class
1    [TYPE]              CLASS_PARAMETER_3
1    [COMMA]             ,
1    [TYPE]              class
1    [TYPE]              CLASS_PARAMETER_4
1    [COMMA]             ,
1    [NEWLINE]           
1    [TYPE]              class
1    [TYPE]              CLASS_PARAMETER_5
1    [ANGLE_CLOSE]       >
1    [NEWLINE]           
2    [CLASS]             class
2    [TYPE]              MyTemplateClass
2    [NEWLINE]           
3    [BRACE_OPEN]        {
3    [NEWLINE]           
4    [PRIVATE]           public
4    [PRIVATE_COLON]     :
4    [NEWLINE]           
5    [TYPE]              MyTemplateClass
5    [ANGLE_OPEN]        <
5    [TYPE]              my
5    [DC_MEMBER]         ::
5    [TYPE]              super
5    [DC_MEMBER]         ::
5    [TYPE]              cool
5    [DC_MEMBER]         ::
5    [TYPE]              _and
5    [DC_MEMBER]         ::
5    [TYPE]              fancy
5    [DC_MEMBER]         ::
5    [TYPE]              type
5    [COMMA]             ,
5    [TYPE]              my
5    [DC_MEMBER]         ::
5    [TYPE]              super
5    [DC_MEMBER]         ::
5    [TYPE]              cool
5    [DC_MEMBER]         ::
5    [TYPE]              _and
5    [DC_MEMBER]         ::
5    [TYPE]              fancy
5    [DC_MEMBER]         ::
5    [TYPE]              type
5    [COMMA]             ,
5    [TYPE]              my
5    [DC_MEMBER]         ::
5    [TYPE]              super
5    [DC_MEMBER]         ::
5    [TYPE]              cool
5    [DC_MEMBER]         ::
5    [TYPE]              _and
5    [DC_MEMBER]         ::
5    [TYPE]              fancy
5    [DC_MEMBER]         ::
5    [TYPE]              type
5    [COMMA]             ,
5    [NEWLINE]           
5    [TYPE]              my
5    [DC_MEMBER]         ::
5    [TYPE]              super
5    [DC_MEMBER]         ::
5    [TYPE]              cool
5    [DC_MEMBER]         ::
5    [TYPE]              _and
5    [DC_MEMBER]         ::
5    [TYPE]              fancy
5    [DC_MEMBER]         ::
5    [TYPE]              type
5    [COMMA]             ,
5    [TYPE]              my
5    [DC_MEMBER]         ::
5    [TYPE]              super
5    [DC_MEMBER]         ::
5    [TYPE]              cool
5    [DC_MEMBER]         ::
5    [TYPE]              _and
5    [DC_MEMBER]         ::
5    [TYPE]              fancy
5    [DC_MEMBER]         ::
5    [TYPE]              type
5    [COMMA]             ,
5    [TYPE]              my
5    [DC_MEMBER]         ::
5    [TYPE]              super
5    [DC_MEMBER]         ::
5    [TYPE]              cool
5    [DC_MEMBER]         ::
5    [TYPE]              _and
5    [DC_MEMBER]         ::
5    [TYPE]              fancy
5    [DC_MEMBER]         ::
5    [TYPE]              type
5    [ANGLE_CLOSE]       >
5    [FUNC_PROTO]        foo
5    [FPAREN_OPEN]       (
5    [FPAREN_CLOSE]      )
5    [SEMICOLON]         ;
5    [NEWLINE]           
6    [BRACE_CLOSE]       }
6    [SEMICOLON]         ;
6    [NEWLINE]           