Line [Token]             Text
1    [FUNC_CALL]         WRAP_FUNCTION
1    [FPAREN_OPEN]       (
1    [WORD]              Foo
1    [COMMA]             ,
1    [WORD]              Bar
1    [ARITH]             &
1    [PAREN_OPEN]        (
1    [TYPE]              void
1    [PAREN_CLOSE]       )
1    [FPAREN_CLOSE]      )
1    [SEMICOLON]         ;
1    [NEWLINE]           
2    [FUNC_CALL]         WRAP_FUNCTION
2    [FPAREN_OPEN]       (
2    [WORD]              Foo
2    [COMMA]             ,
2    [WORD]              Bar
2    [ARITH]             *
2    [PAREN_OPEN]        (
2    [TYPE]              void
2    [PAREN_CLOSE]       )
2    [FPAREN_CLOSE]      )
2    [SEMICOLON]         ;
2    [NEWLINE]           
3    [FUNC_CALL]         WRAP_FUNCTION
3    [FPAREN_OPEN]       (
3    [WORD]              Foo
3    [COMMA]             ,
3    [PAREN_OPEN]        (
3    [WORD]              Bar
3    [ARITH]             &
3    [PAREN_OPEN]        (
3    [TYPE]              void
3    [PAREN_CLOSE]       )
3    [PAREN_CLOSE]       )
3    [FPAREN_CLOSE]      )
3    [SEMICOLON]         ;
3    [NEWLINE]           
4    [FUNC_CALL]         WRAP_FUNCTION
4    [FPAREN_OPEN]       (
4    [WORD]              Foo
4    [COMMA]             ,
4    [PAREN_OPEN]        (
4    [WORD]              Bar
4    [ARITH]             *
4    [PAREN_OPEN]        (
4    [TYPE]              void
4    [PAREN_CLOSE]       )
4    [PAREN_CLOSE]       )
4    [FPAREN_CLOSE]      )
4    [SEMICOLON]         ;
4    [NEWLINE]           