Line [Token]             Text
1    [TYPE]              void
1    [TYPE]              Foo
1    [DC_MEMBER]         ::
1    [FUNC_DEF]          doo
1    [FPAREN_OPEN]       (
1    [FPAREN_CLOSE]      )
1    [NEWLINE]           
2    [BRACE_OPEN]        {
2    [NEWLINE]           
3    [TYPE]              m_stackCache
3    [SQUARE_OPEN]       [
3    [TYPE]              m_currentStackNr
3    [SQUARE_CLOSE]      ]
3    [MEMBER]            ->
3    [OPERATOR]          operator
3    [FUNC_CALL]         []
3    [FPAREN_OPEN]       (
3    [NUMBER]            0
3    [FPAREN_CLOSE]      )
3    [ASSIGN]            =
3    [NEW]               new
3    [FUNC_CALL]         QStandardItem
3    [FPAREN_OPEN]       (
3    [TYPE]              QString
3    [DC_MEMBER]         ::
3    [FUNC_CALL]         number
3    [FPAREN_OPEN]       (
3    [WORD]              m_currentStackNr
3    [FPAREN_CLOSE]      )
3    [FPAREN_CLOSE]      )
3    [SEMICOLON]         ;
3    [NEWLINE]           
4    [TYPE]              m_stackCache
4    [SQUARE_OPEN]       [
4    [TYPE]              m_currentStackNr
4    [SQUARE_CLOSE]      ]
4    [MEMBER]            ->
4    [OPERATOR]          operator
4    [FUNC_CALL]         []
4    [FPAREN_OPEN]       (
4    [NUMBER]            1
4    [FPAREN_CLOSE]      )
4    [ASSIGN]            =
4    [NEW]               new
4    [FUNC_CALL]         QStandardItem
4    [FPAREN_OPEN]       (
4    [FUNC_CALL]         tr
4    [FPAREN_OPEN]       (
4    [STRING]            "OK"
4    [FPAREN_CLOSE]      )
4    [FPAREN_CLOSE]      )
4    [SEMICOLON]         ;
4    [NEWLINE]           
5    [TYPE]              m_stackCache
5    [SQUARE_OPEN]       [
5    [TYPE]              m_currentStackNr
5    [SQUARE_CLOSE]      ]
5    [MEMBER]            ->
5    [OPERATOR]          operator
5    [FUNC_CALL]         []
5    [FPAREN_OPEN]       (
5    [NUMBER]            2
5    [FPAREN_CLOSE]      )
5    [ASSIGN]            =
5    [NEW]               new
5    [FUNC_CALL]         QStandardItem
5    [FPAREN_OPEN]       (
5    [STRING]            "0"
5    [FPAREN_CLOSE]      )
5    [SEMICOLON]         ;
5    [NEWLINE]           
6    [TYPE]              m_stackCache
6    [SQUARE_OPEN]       [
6    [TYPE]              m_currentStackNr
6    [SQUARE_CLOSE]      ]
6    [MEMBER]            ->
6    [OPERATOR]          operator
6    [FUNC_CALL]         []
6    [FPAREN_OPEN]       (
6    [NUMBER]            3
6    [FPAREN_CLOSE]      )
6    [ASSIGN]            =
6    [NEW]               new
6    [FUNC_CALL]         QStandardItem
6    [FPAREN_OPEN]       (
6    [STRING]            "0"
6    [FPAREN_CLOSE]      )
6    [SEMICOLON]         ;
6    [NEWLINE]           
7    [TYPE]              m_stackCache
7    [SQUARE_OPEN]       [
7    [TYPE]              m_currentStackNr
7    [SQUARE_CLOSE]      ]
7    [MEMBER]            ->
7    [OPERATOR]          operator
7    [FUNC_CALL]         []
7    [FPAREN_OPEN]       (
7    [NUMBER]            4
7    [FPAREN_CLOSE]      )
7    [ASSIGN]            =
7    [NEW]               new
7    [FUNC_CALL]         QStandardItem
7    [FPAREN_OPEN]       (
7    [FPAREN_CLOSE]      )
7    [SEMICOLON]         ;
7    [NEWLINE]           
8    [BRACE_CLOSE]       }
8    [NEWLINE]           