Line [Token]             Text
1    [TYPE]              Foo
1    [PTR_TYPE]          *
1    [WORD]              foo
1    [ASSIGN]            =
1    [NEW]               new
1    [FUNC_CALL]         Foo
1    [FPAREN_OPEN]       (
1    [WORD]              a
1    [COMMA]             ,
1    [WORD]              v
1    [FPAREN_CLOSE]      )
1    [SEMICOLON]         ;
1    [NEWLINE]           
3    [TYPE]              Foo
3    [PTR_TYPE]          *
3    [WORD]              foo
3    [ASSIGN]            =
3    [NEW]               new
3    [PAREN_OPEN]        (
3    [WORD]              ptr
3    [COMMA]             ,
3    [TYPE]              std
3    [DC_MEMBER]         ::
3    [WORD]              nothrow
3    [PAREN_CLOSE]       )
3    [WORD]              Foo
3    [TSQUARE]           []
3    [SEMICOLON]         ;
3    [NEWLINE]           
4    [TYPE]              Foo
4    [PTR_TYPE]          *
4    [WORD]              foo
4    [ASSIGN]            =
4    [NEW]               new
4    [PAREN_OPEN]        (
4    [WORD]              ptr
4    [PAREN_CLOSE]       )
4    [FUNC_CALL]         Foo
4    [FPAREN_OPEN]       (
4    [FPAREN_CLOSE]      )
4    [SEMICOLON]         ;
4    [NEWLINE]           
5    [TYPE]              Foo
5    [PTR_TYPE]          *
5    [WORD]              foo
5    [ASSIGN]            =
5    [NEW]               new
5    [PAREN_OPEN]        (
5    [FUNC_CALL]         FOO
5    [FPAREN_OPEN]       (
5    [WORD]              ptr
5    [FPAREN_CLOSE]      )
5    [PAREN_CLOSE]       )
5    [FUNC_CALL]         Foo
5    [FPAREN_OPEN]       (
5    [FPAREN_CLOSE]      )
5    [SEMICOLON]         ;
5    [NEWLINE]           
7    [TYPE]              Foo
7    [PTR_TYPE]          *
7    [WORD]              foo
7    [ASSIGN]            =
7    [NEW]               new
7    [PAREN_OPEN]        (
7    [WORD]              ptr
7    [COMMA]             ,
7    [TYPE]              std
7    [DC_MEMBER]         ::
7    [WORD]              nothrow
7    [PAREN_CLOSE]       )
7    [WORD]              Foo
7    [TSQUARE]           []
7    [SEMICOLON]         ;
7    [NEWLINE]           
8    [TYPE]              Foo
8    [PTR_TYPE]          *
8    [WORD]              foo
8    [ASSIGN]            =
8    [NEW]               new
8    [PAREN_OPEN]        (
8    [WORD]              ptr
8    [PAREN_CLOSE]       )
8    [FUNC_CALL]         Foo
8    [FPAREN_OPEN]       (
8    [FPAREN_CLOSE]      )
8    [SEMICOLON]         ;
8    [NEWLINE]           
9    [TYPE]              Foo
9    [PTR_TYPE]          *
9    [WORD]              foo
9    [ASSIGN]            =
9    [NEW]               new
9    [PAREN_OPEN]        (
9    [FUNC_CALL]         FOO
9    [FPAREN_OPEN]       (
9    [WORD]              ptr
9    [FPAREN_CLOSE]      )
9    [PAREN_CLOSE]       )
9    [FUNC_CALL]         Foo
9    [FPAREN_OPEN]       (
9    [FPAREN_CLOSE]      )
9    [SEMICOLON]         ;
9    [NEWLINE]           