Line [Token]             Text
1    [DC_MEMBER]         ::
1    [TYPE]              some
1    [DC_MEMBER]         ::
1    [TYPE]              very
1    [DC_MEMBER]         ::
1    [TYPE]              looong
1    [DC_MEMBER]         ::
1    [TYPE]              _and
1    [DC_MEMBER]         ::
1    [TYPE]              complicated
1    [DC_MEMBER]         ::
1    [TYPE]              name
1    [DC_MEMBER]         ::
1    [TYPE]              MyType
1    [BYREF]             &
1    [WORD]              a
1    [SEMICOLON]         ;