Line [Token]             Text
1    [TYPE]              int
1    [WORD]              i
1    [ASSIGN]            =
1    [NUMBER]            0
1    [ARITH]             +
1    [NUMBER]            3
1    [ARITH]             -
1    [NUMBER]            4
1    [ARITH]             *
1    [NUMBER]            3
1    [ARITH]             %
1    [NUMBER]            3
1    [SEMICOLON]         ;
1    [NEWLINE]           
2    [TYPE]              int
2    [WORD]              ii
2    [ASSIGN]            =
2    [NUMBER]            0
2    [ARITH]             +
2    [NUMBER]            3
2    [ARITH]             -
2    [NUMBER]            4
2    [ARITH]             *
2    [NUMBER]            3
2    [ARITH]             %
2    [NUMBER]            3
2    [SEMICOLON]         ;