Line [Parent]            Text
1    [NONE]              NSString
1    [NONE]              *
1    [NONE]              str
1    [NONE]              =
1    [NONE]              (
1    [NONE]              otherString
1    [NONE]              ?
1    [NONE]              :
1    [NONE]              @"this is the placeholder"
1    [NONE]              )
1    [NONE]              ;
1    [NONE]              
2    [NONE]              NSString
2    [NONE]              *
2    [NONE]              str2
2    [NONE]              =
2    [NONE]              (
2    [NONE]              str
2    [NONE]              ?
2    [NONE]              otherString
2    [NONE]              :
2    [NONE]              @"this is the other placeholder"
2    [NONE]              )
2    [NONE]              ;
2    [NONE]              
3    [NONE]              NSString
3    [NONE]              *
3    [NONE]              str3
3    [NONE]              =
3    [NONE]              str
3    [NONE]              ?
3    [OC_MSG]            [
3    [OC_MSG]            [
3    [NONE]              NSString
3    [NONE]              alloc
3    [OC_MSG]            ]
3    [NONE]              initWithString
3    [NONE]              :
3    [NONE]              str
3    [OC_MSG]            ]
3    [NONE]              :
3    [NONE]              @"this is the third placeholder"
3    [NONE]              ;
3    [NONE]              
4    [NONE]              id
4    [NONE]              str4
4    [NONE]              =
4    [NONE]              str
4    [NONE]              ?
4    [OC_MSG]            [
4    [NONE]              self
4    [NONE]              methodWithParameter1
4    [NONE]              :
4    [NONE]              @
4    [OC_AT]             {
4    [NONE]              @"bla"
4    [NONE]              :
4    [NONE]              (
4    [NONE]              {
4    [OC_MSG]            [
4    [NONE]              self
4    [NONE]              anotherMethod
4    [NONE]              :
4    [NONE]              @
4    [OC_AT]             {
4    [NONE]              @"id"
4    [NONE]              :
4    [NONE]              @1
4    [OC_AT]             }
4    [OC_MSG]            ]
4    [OC_MSG]            ;
4    [NONE]              
4    [NONE]              }
4    [NONE]              )
4    [OC_AT]             }
4    [NONE]              
5    [NONE]              andParameter2
5    [OC_MSG_NAME]       :
5    [NONE]              @
5    [OC_AT]             {
5    [NONE]              @"dict_key"
5    [NONE]              :
5    [NONE]              @
5    [OC_AT]             {
5    [NONE]              @"nested_dict_key_1"
5    [NONE]              :
5    [NONE]              @
5    [OC_AT]             (
5    [NONE]              1
5    [OC_AT]             )
5    [NONE]              ,
5    [NONE]              @"nested_dict_key_2"
5    [NONE]              :
5    [NONE]              @"colon:in:string"
5    [OC_AT]             }
5    [OC_AT]             }
5    [OC_MSG]            ]
5    [NONE]              :
5    [OC_MSG]            [
5    [NONE]              self
5    [NONE]              anotherMethod
5    [NONE]              :
5    [NONE]              str
5    [NONE]              ?
5    [NONE]              @1
5    [NONE]              :
5    [NONE]              @2
5    [OC_MSG]            ]
5    [OC_MSG]            ;
5    [NONE]              