Line [Parent]            Text
1    [NONE]              @interface
1    [OC_INTF]           UCTestClass
1    [OC_INTF]           (
1    [OC_INTF]           )
1    [NONE]              
3    [NONE]              @property
3    [OC_PROPERTY]       (
3    [NONE]              nonatomic
3    [NONE]              ,
3    [NONE]              readonly
3    [NONE]              ,
3    [NONE]              strong
3    [NONE]              ,
3    [NONE]              null_unspecified
3    [OC_PROPERTY]       )
3    [NONE]              NSString
3    [NONE]              *
3    [NONE]              test1
3    [OC_PROPERTY]       ;
3    [NONE]              
4    [NONE]              @property
4    [OC_PROPERTY]       (
4    [NONE]              nonatomic
4    [NONE]              ,
4    [NONE]              readonly
4    [NONE]              ,
4    [NONE]              strong
4    [NONE]              ,
4    [NONE]              nullable
4    [OC_PROPERTY]       )
4    [NONE]              NSString
4    [NONE]              *
4    [NONE]              test2
4    [OC_PROPERTY]       ;
4    [NONE]              
5    [NONE]              @property
5    [OC_PROPERTY]       (
5    [NONE]              nonatomic
5    [NONE]              ,
5    [NONE]              readonly
5    [NONE]              ,
5    [NONE]              strong
5    [NONE]              ,
5    [NONE]              nonnull
5    [NONE]              ,
5    [NONE]              getter
5    [NONE]              =
5    [NONE]              test2Getter
5    [OC_PROPERTY]       )
5    [NONE]              NSString
5    [NONE]              *
5    [NONE]              test3
5    [OC_PROPERTY]       ;
5    [NONE]              
6    [NONE]              @property
6    [OC_PROPERTY]       (
6    [NONE]              nonatomic
6    [NONE]              ,
6    [NONE]              readonly
6    [NONE]              ,
6    [NONE]              strong
6    [NONE]              ,
6    [NONE]              null_resettable
6    [NONE]              ,
6    [NONE]              getter
6    [NONE]              =
6    [NONE]              test2Getter
6    [NONE]              ,
6    [NONE]              setter
6    [NONE]              =
6    [NONE]              test2Setter
6    [NONE]              :
6    [OC_PROPERTY]       )
6    [NONE]              NSString
6    [NONE]              *
6    [NONE]              test4
6    [OC_PROPERTY]       ;
6    [NONE]              
8    [OC_INTF]           @end
8    [NONE]              