Line [Parent]            Text
1    [PP_INCLUDE]        #
1    [NONE]              import
1    [NONE]              <Foundation/Foundation.h>
1    [NONE]              
3    [PP_DEFINE]         #
3    [NONE]              define
3    [NONE]              UIColorFromRGB
3    [MACRO_FUNC]        (
3    [NONE]              rgbValue
3    [MACRO_FUNC]        )
3    [OC_MSG]            [
3    [NONE]              UIColor
3    [NONE]              colorWithRed
3    [NONE]              :
3    [NONE]              (
3    [C_CAST]            (
3    [C_CAST]            float
3    [C_CAST]            )
3    [NONE]              (
3    [NONE]              (
3    [NONE]              rgbValue
3    [NONE]              &
3    [NONE]              0xFF0000
3    [NONE]              )
3    [NONE]              >>
3    [NONE]              16
3    [NONE]              )
3    [NONE]              )
3    [NONE]              /
3    [NONE]              255.0
3    [NONE]              green
3    [OC_MSG_NAME]       :
3    [NONE]              (
3    [C_CAST]            (
3    [C_CAST]            float
3    [C_CAST]            )
3    [NONE]              (
3    [NONE]              (
3    [NONE]              rgbValue
3    [NONE]              &
3    [NONE]              0xFF00
3    [NONE]              )
3    [NONE]              >>
3    [NONE]              8
3    [NONE]              )
3    [NONE]              )
3    [NONE]              /
3    [NONE]              255.0
3    [NONE]              blue
3    [OC_MSG_NAME]       :
3    [NONE]              (
3    [C_CAST]            (
3    [C_CAST]            float
3    [C_CAST]            )
3    [NONE]              (
3    [NONE]              rgbValue
3    [NONE]              &
3    [NONE]              0xFF
3    [NONE]              )
3    [NONE]              )
3    [NONE]              /
3    [NONE]              255.0
3    [NONE]              alpha
3    [OC_MSG_NAME]       :
3    [NONE]              1.0
3    [OC_MSG]            ]
3    [NONE]              
5    [PP_IF]             #
5    [NONE]              if
5    [NONE]              TARGET_OS_IPHONE
5    [NONE]              
6    [PP_DEFINE]         #
6    [NONE]              define
6    [NONE]              GL_CONTEXT_ALLOC
6    [MACRO_FUNC]        (
6    [NONE]              parentContext
6    [MACRO_FUNC]        )
6    [OC_MSG]            [
6    [OC_MSG]            [
6    [NONE]              EAGLContext
6    [NONE]              alloc
6    [OC_MSG]            ]
6    [NONE]              initWithAPI
6    [NONE]              :
6    [NONE]              GL_CONTEXT_VERSION
6    [FUNC_CALL]         (
6    [NONE]              parentContext
6    [FUNC_CALL]         )
6    [NONE]              sharegroup
6    [OC_MSG_NAME]       :
6    [OC_MSG]            [
6    [NONE]              parentContext
6    [NONE]              sharegroup
6    [OC_MSG]            ]
6    [OC_MSG]            ]
6    [NONE]              
7    [PP_ELSE]           #
7    [NONE]              else
7    [NONE]              
8    [PP_DEFINE]         #
8    [NONE]              define
8    [NONE]              GL_CONTEXT_ALLOC
8    [MACRO_FUNC]        (
8    [NONE]              parentContext
8    [MACRO_FUNC]        )
8    [OC_MSG]            [
8    [OC_MSG]            [
8    [NONE]              NSOpenGLContext
8    [NONE]              alloc
8    [OC_MSG]            ]
8    [NONE]              initWithFormat
8    [NONE]              :
8    [OC_MSG]            [
8    [OC_MSG]            [
8    [NONE]              NSOpenGLPixelFormat
8    [NONE]              alloc
8    [OC_MSG]            ]
8    [NONE]              initWithCGLPixelFormatObj
8    [NONE]              :
8    [NONE]              CGLGetPixelFormat
8    [FUNC_CALL]         (
8    [OC_MSG]            [
8    [NONE]              parentContext
8    [NONE]              CGLContextObj
8    [OC_MSG]            ]
8    [FUNC_CALL]         )
8    [OC_MSG]            ]
8    [NONE]              shareContext
8    [OC_MSG_NAME]       :
8    [NONE]              parentContext
8    [OC_MSG]            ]
8    [NONE]              
9    [PP_ENDIF]          #
9    [NONE]              endif
9    [NONE]              
11   [PP_DEFINE]         #
11   [NONE]              define
11   [NONE]              NSLocalizedString
11   [MACRO_FUNC]        (
11   [NONE]              key
11   [NONE]              ,
11   [NONE]              comment
11   [MACRO_FUNC]        )
11   [NONE]              \
12   [OC_MSG]            [
12   [NONE]              TestClassBundle
12   [NONE]              localizedStringForKey
12   [NONE]              :
12   [NONE]              (
12   [NONE]              key
12   [NONE]              )
12   [NONE]              value
12   [OC_MSG_NAME]       :
12   [NONE]              @""
12   [NONE]              table
12   [OC_MSG_NAME]       :
12   [NONE]              nil
12   [OC_MSG]            ]
12   [NONE]              
14   [NONE]              @interface
14   [OC_INTF]           TestClass
14   [OC_CLASS]          :
14   [NONE]              NSObject
14   [NONE]              
15   [OC_INTF]           @end
15   [NONE]              
17   [NONE]              @implementation
17   [OC_IMPL]           TestClass
17   [NONE]              
18   [OC_IMPL]           @end
18   [NONE]              