Line [Parent]            Text
1    [PP_INCLUDE]        #
1    [NONE]              import
1    [NONE]              <Foundation/Foundation.h>
1    [NONE]              
3    [PP_DEFINE]         #
3    [NONE]              define
3    [NONE]              MACRO
3    [MACRO_FUNC]        (
3    [NONE]              foo
3    [MACRO_FUNC]        )
3    [NONE]              \
4    [NONE]              if
4    [IF]                (
4    [NONE]              _
4    [NONE]              ##
4    [NONE]              foo
4    [NONE]              ==
4    [NONE]              NULL
4    [IF]                )
4    [IF]                {
4    [NONE]              \
5    [NONE]              Log
5    [FUNC_CALL]         (
5    [NONE]              "do %s"
5    [NONE]              ,
5    [NONE]              str
5    [FUNC_CALL]         (
5    [NONE]              foo
5    [FUNC_CALL]         )
5    [FUNC_CALL]         )
5    [NONE]              ;
5    [NONE]              \
6    [NONE]              _
6    [NONE]              ##
6    [NONE]              foo
6    [NONE]              =
6    [C_CAST]            (
6    [C_CAST]            foo
6    [C_CAST]            ##
6    [C_CAST]            _t
6    [C_CAST]            *
6    [C_CAST]            )
6    [NONE]              process
6    [FUNC_CALL]         (
6    [NONE]              PR_FLAG
6    [NONE]              ,
6    [NONE]              str
6    [FUNC_CALL]         (
6    [NONE]              foo
6    [FUNC_CALL]         )
6    [FUNC_CALL]         )
6    [NONE]              ;
6    [NONE]              \
7    [IF]                }
7    [NONE]              
9    [PP_DEFINE]         #
9    [NONE]              define
9    [NONE]              OVERLOAD
9    [MACRO_FUNC]        (
9    [NONE]              base
9    [NONE]              ,
9    [NONE]              foo
9    [MACRO_FUNC]        )
9    [NONE]              \
10   [NONE]              foo
10   [NONE]              ##
10   [NONE]              _override_t
10   [NONE]              *
10   [NONE]              foo
10   [NONE]              ##
10   [NONE]              _bar
10   [NONE]              =
10   [C_CAST]            (
10   [C_CAST]            foo
10   [C_CAST]            ##
10   [C_CAST]            _override_t
10   [C_CAST]            *
10   [C_CAST]            )
10   [NONE]              process
10   [FUNC_CALL]         (
10   [NONE]              base
10   [NONE]              ##
10   [NONE]              _bar
10   [NONE]              ,
10   [NONE]              str
10   [FUNC_CALL]         (
10   [NONE]              foo
10   [FUNC_CALL]         )
10   [FUNC_CALL]         )
10   [NONE]              ;
10   [NONE]              \
11   [NONE]              _
11   [NONE]              ##
11   [NONE]              foo
11   [NONE]              ##
11   [NONE]              _override
11   [NONE]              =
11   [C_CAST]            (
11   [C_CAST]            foo
11   [C_CAST]            ##
11   [C_CAST]            _override_t
11   [C_CAST]            *
11   [C_CAST]            )
11   [NONE]              process
11   [FUNC_CALL]         (
11   [NONE]              base
11   [NONE]              ##
11   [NONE]              _cache
11   [NONE]              ,
11   [NONE]              str
11   [FUNC_CALL]         (
11   [NONE]              foo
11   [FUNC_CALL]         )
11   [FUNC_CALL]         )
11   [NONE]              ;
11   [NONE]              