Line [Parent]            Text
1    [NONE]              
2    [PP_DEFINE]         #
2    [NONE]              define
2    [NONE]              foobar
2    [MACRO_FUNC]        (
2    [NONE]              x
2    [MACRO_FUNC]        )
2    [NONE]              \
3    [NONE]              {
3    [NONE]              \
4    [NONE]              for
4    [FOR]               (
4    [NONE]              i
4    [NONE]              =
4    [NONE]              0
4    [FOR]               ;
4    [NONE]              i
4    [NONE]              <
4    [NONE]              x
4    [FOR]               ;
4    [NONE]              i
4    [NONE]              ++
4    [FOR]               )
4    [NONE]              \
5    [FOR]               {
5    [NONE]              \
6    [NONE]              junk
6    [FUNC_CALL]         (
6    [NONE]              i
6    [NONE]              ,
6    [NONE]              x
6    [FUNC_CALL]         )
6    [NONE]              ;
6    [NONE]              \
7    [FOR]               }
7    [NONE]              \
8    [NONE]              }
8    [NONE]              