Line [Parent]            Text
1    [FUNC_DEF]          void
1    [NONE]              foo
1    [FUNC_DEF]          (
1    [NONE]              int
1    [NONE]              *
1    [NONE]              pA
1    [NONE]              ,
1    [NONE]              int
1    [NONE]              *
1    [NONE]              pB
1    [FUNC_DEF]          )
1    [NONE]              
2    [FUNC_DEF]          {
2    [NONE]              
3    [NONE]              *
3    [NONE]              pB
3    [NONE]              =
3    [NONE]              some
3    [NONE]              .
3    [NONE]              arr
3    [NONE]              [
3    [NONE]              *
3    [NONE]              pA
3    [NONE]              ]
3    [NONE]              ;
3    [NONE]              
5    [NONE]              foo
5    [FUNC_CALL]         (
5    [NONE]              sizeof
5    [NONE]              bar
5    [NONE]              /
5    [NONE]              sizeof
5    [NONE]              *
5    [NONE]              bar
5    [NONE]              ,
5    [NONE]              baz
5    [FUNC_CALL]         )
5    [NONE]              ;
5    [NONE]              
7    [FUNC_DEF]          }
7    [NONE]              
9    [PP_DEFINE]         #
9    [NONE]              define
9    [NONE]              MEM_READ_BYTE
9    [MACRO_FUNC]        (
9    [NONE]              phwi
9    [NONE]              ,
9    [NONE]              addr
9    [NONE]              ,
9    [NONE]              data
9    [MACRO_FUNC]        )
9    [NONE]              \
10   [NONE]              *
10   [NONE]              data
10   [NONE]              =
10   [NONE]              *
10   [NONE]              (
10   [C_CAST]            (
10   [C_CAST]            PUCHAR
10   [C_CAST]            )
10   [NONE]              (
10   [NONE]              (
10   [NONE]              phwi
10   [NONE]              )
10   [NONE]              ->
10   [NONE]              m_pVirtualMemory
10   [NONE]              +
10   [NONE]              addr
10   [NONE]              )
10   [NONE]              )
10   [NONE]              
12   [PP_DEFINE]         #
12   [NONE]              define
12   [NONE]              MEM_WRITE_BYTE
12   [MACRO_FUNC]        (
12   [NONE]              phwi
12   [NONE]              ,
12   [NONE]              addr
12   [NONE]              ,
12   [NONE]              data
12   [MACRO_FUNC]        )
12   [NONE]              \
13   [NONE]              *
13   [NONE]              (
13   [C_CAST]            (
13   [C_CAST]            PUCHAR
13   [C_CAST]            )
13   [NONE]              (
13   [NONE]              (
13   [NONE]              phwi
13   [NONE]              )
13   [NONE]              ->
13   [NONE]              m_pVirtualMemory
13   [NONE]              +
13   [NONE]              addr
13   [NONE]              )
13   [NONE]              )
13   [NONE]              =
13   [C_CAST]            (
13   [C_CAST]            UCHAR
13   [C_CAST]            )
13   [NONE]              (
13   [NONE]              data
13   [NONE]              )
13   [NONE]              