Line [Parent]            Text
1    [PP_DEFINE]         #
1    [NONE]              define
1    [NONE]              UHI_AOA
1    [NONE]              {
1    [NONE]              \
2    [NONE]              .
2    [C99_MEMBER]        install
2    [NONE]              =
2    [NONE]              uhi_aoa_install
2    [NONE]              ,
2    [NONE]              \
3    [NONE]              .
3    [C99_MEMBER]        enable
3    [NONE]              =
3    [NONE]              uhi_aoa_enable
3    [NONE]              ,
3    [NONE]              \
4    [NONE]              .
4    [C99_MEMBER]        uninstall
4    [NONE]              =
4    [NONE]              uhi_aoa_uninstall
4    [NONE]              ,
4    [NONE]              \
5    [NONE]              .
5    [C99_MEMBER]        sof_notify
5    [NONE]              =
5    [NONE]              NULL
5    [NONE]              ,
5    [NONE]              \
6    [NONE]              }
6    [NONE]              