Line [Parent]            Text
1    [FUNC_PROTO]        void
1    [NONE]              foo1
1    [FUNC_PROTO]        (
1    [NONE]              int
1    [NONE]              param1
1    [NONE]              ,
1    [NONE]              int
1    [NONE]              param2
1    [NONE]              ,
1    [NONE]              char
1    [NONE]              *
1    [NONE]              param2
1    [FUNC_PROTO]        )
1    [FUNC_PROTO]        ;
1    [NONE]              
3    [FUNC_PROTO]        void
3    [NONE]              foo2
3    [FUNC_PROTO]        (
3    [NONE]              int
3    [NONE]              param1
3    [NONE]              ,
4    [NONE]              int
4    [NONE]              param2
4    [NONE]              ,
5    [NONE]              char
5    [NONE]              *
5    [NONE]              param2
5    [FUNC_PROTO]        )
5    [FUNC_PROTO]        ;
5    [NONE]              
7    [FUNC_PROTO]        void
7    [NONE]              foo3
7    [FUNC_PROTO]        (
7    [NONE]              int
7    [NONE]              param1
7    [NONE]              ,
8    [NONE]              int
8    [NONE]              param2
8    [NONE]              ,
9    [NONE]              char
9    [NONE]              *
9    [NONE]              param2
10   [FUNC_PROTO]        )
10   [FUNC_PROTO]        ;
10   [NONE]              
12   [FUNC_PROTO]        struct
12   [FUNC_PROTO]        whoopee
12   [FUNC_PROTO]        *
12   [NONE]              foo4
12   [FUNC_PROTO]        (
12   [NONE]              int
12   [NONE]              param1
12   [NONE]              ,
12   [NONE]              int
12   [NONE]              param2
12   [NONE]              ,
12   [NONE]              char
12   [NONE]              *
12   [NONE]              param2
12   [FUNC_PROTO]        )
12   [FUNC_PROTO]        ;
12   [NONE]              
14   [FUNC_PROTO]        const
14   [FUNC_PROTO]        struct
14   [FUNC_PROTO]        snickers
14   [FUNC_PROTO]        *
15   [NONE]              foo5
15   [FUNC_PROTO]        (
15   [NONE]              int
15   [NONE]              param1
15   [NONE]              ,
15   [NONE]              int
15   [NONE]              param2
15   [NONE]              ,
15   [NONE]              char
15   [NONE]              *
15   [NONE]              param2
15   [FUNC_PROTO]        )
15   [FUNC_PROTO]        ;
15   [NONE]              
18   [FUNC_DEF]          void
18   [NONE]              foo
18   [FUNC_DEF]          (
18   [NONE]              int
18   [NONE]              param1
18   [NONE]              ,
18   [NONE]              int
18   [NONE]              param2
18   [NONE]              ,
18   [NONE]              char
18   [NONE]              *
18   [NONE]              param2
18   [FUNC_DEF]          )
18   [NONE]              
19   [FUNC_DEF]          {
19   [NONE]              
20   [NONE]              printf
20   [FUNC_CALL]         (
20   [NONE]              "boo!\n"
20   [FUNC_CALL]         )
20   [NONE]              ;
20   [NONE]              
21   [FUNC_DEF]          }
21   [NONE]              
23   [FUNC_PROTO]        EXPORT
23   [FUNC_PROTO]        int
23   [NONE]              DoStuff
23   [FUNC_PROTO]        (
23   [NONE]              int
23   [NONE]              Num
23   [FUNC_PROTO]        )
23   [FUNC_PROTO]        ;
23   [NONE]              