Line [Token]             Text
1    [QUALIFIER]         static
1    [TYPE]              int32_t
1    [FUNC_PROTO]        level_and_name_to_system
1    [FPAREN_OPEN]       (
1    [TYPE]              SocketOptionLevel
1    [WORD]              level
1    [COMMA]             ,
1    [TYPE]              SocketOptionName
1    [WORD]              name
1    [COMMA]             ,
1    [TYPE]              int32_t
1    [PTR_TYPE]          *
1    [WORD]              system_level
1    [COMMA]             ,
1    [TYPE]              int32_t
1    [PTR_TYPE]          *
1    [WORD]              system_name
1    [FPAREN_CLOSE]      )
1    [NEWLINE]           
3    [TYPE]              WaitStatus
3    [FUNC_PROTO]        SendTo
3    [FPAREN_OPEN]       (
3    [TYPE]              uint8_t
3    [WORD]              address
3    [SQUARE_OPEN]       [
3    [WORD]              ipv6AddressSize
3    [SQUARE_CLOSE]      ]
3    [COMMA]             ,
3    [TYPE]              uint32_t
3    [WORD]              scope
3    [COMMA]             ,
3    [TYPE]              uint16_t
3    [WORD]              port
3    [COMMA]             ,
3    [QUALIFIER]         const
3    [TYPE]              uint8_t
3    [PTR_TYPE]          *
3    [WORD]              data
3    [COMMA]             ,
3    [TYPE]              int32_t
3    [WORD]              count
3    [COMMA]             ,
3    [TYPE]              os
3    [DC_MEMBER]         ::
3    [TYPE]              SocketFlags
3    [WORD]              flags
3    [COMMA]             ,
3    [TYPE]              int32_t
3    [PTR_TYPE]          *
3    [WORD]              len
3    [FPAREN_CLOSE]      )
3    [SEMICOLON]         ;
3    [NEWLINE]           