Line [Token]             Text
1    [QUALIFIER]         static
1    [TYPE]              void
1    [FUNC_PROTO]        WriteArrayToDrag
1    [FPAREN_OPEN]       (
1    [TYPE]              NSArray
1    [PTR_TYPE]          *
1    [WORD]              array
1    [COMMA]             ,
1    [TYPE]              NSPasteboard
1    [PTR_TYPE]          *
1    [WORD]              pboard
1    [COMMA]             ,
1    [TYPE]              NSString
1    [PTR_TYPE]          *
1    [WORD]              pboardType
1    [FPAREN_CLOSE]      )
1    [SEMICOLON]         ;
1    [NEWLINE]           
2    [QUALIFIER]         static
2    [TYPE]              OSStatus
2    [FUNC_PROTO]        FindProcess
2    [FPAREN_OPEN]       (
2    [QUALIFIER]         const
2    [TYPE]              FSRef
2    [PTR_TYPE]          *
2    [WORD]              appRef
2    [COMMA]             ,
2    [TYPE]              ProcessSerialNumber
2    [PTR_TYPE]          *
2    [WORD]              pPSN
2    [COMMA]             ,
2    [TYPE]              NSString
2    [PTR_TYPE]          *
2    [WORD]              application
2    [COMMA]             ,
2    [TYPE]              bool
2    [WORD]              permissiveSearching
2    [FPAREN_CLOSE]      )
2    [SEMICOLON]         ;
2    [NEWLINE]           
3    [TYPE]              NSString
3    [PTR_TYPE]          *
3    [FUNC_PROTO]        MakeNSString
3    [FPAREN_OPEN]       (
3    [QUALIFIER]         const
3    [TYPE]              std
3    [DC_MEMBER]         ::
3    [TYPE]              string
3    [BYREF]             &
3    [WORD]              string
3    [FPAREN_CLOSE]      )
3    [SEMICOLON]         ;
3    [NEWLINE]           