Line [Token]             Text
1    [FUNC_CALL]         CGPathMoveToPoint
1    [FPAREN_OPEN]       (
1    [WORD]              bottomArrow
1    [COMMA]             ,
1    [WORD]              NULL
1    [COMMA]             ,
1    [FUNC_CALL]         round
1    [FPAREN_OPEN]       (
1    [WORD]              aPoint
1    [MEMBER]            .
1    [WORD]              x
1    [FPAREN_CLOSE]      )
1    [ARITH]             +
1    [NUMBER_FP]         .5
1    [ARITH]             /
1    [WORD]              self
1    [MEMBER]            .
1    [WORD]              contentsScale
1    [ARITH]             -
1    [NUMBER]            3
1    [COMMA]             ,
1    [WORD]              aPoint
1    [MEMBER]            .
1    [WORD]              y
1    [ARITH]             -
1    [WORD]              aLength
1    [ARITH]             +
1    [NUMBER]            1
1    [ARITH]             +
1    [NUMBER]            4
1    [FPAREN_CLOSE]      )
1    [SEMICOLON]         ;
1    [NEWLINE]           
2    [FUNC_CALL]         CGPathAddLineToPoint
2    [FPAREN_OPEN]       (
2    [WORD]              bottomArrow
2    [COMMA]             ,
2    [WORD]              NULL
2    [COMMA]             ,
2    [FUNC_CALL]         round
2    [FPAREN_OPEN]       (
2    [WORD]              aPoint
2    [MEMBER]            .
2    [WORD]              x
2    [FPAREN_CLOSE]      )
2    [ARITH]             +
2    [NUMBER_FP]         .5
2    [ARITH]             /
2    [WORD]              self
2    [MEMBER]            .
2    [WORD]              contentsScale
2    [COMMA]             ,
2    [WORD]              aPoint
2    [MEMBER]            .
2    [WORD]              y
2    [ARITH]             -
2    [WORD]              aLength
2    [ARITH]             +
2    [NUMBER]            1
2    [FPAREN_CLOSE]      )
2    [SEMICOLON]         ;
2    [NEWLINE]           
3    [FUNC_CALL]         CGPathAddLineToPoint
3    [FPAREN_OPEN]       (
3    [WORD]              bottomArrow
3    [COMMA]             ,
3    [WORD]              NULL
3    [COMMA]             ,
3    [FUNC_CALL]         round
3    [FPAREN_OPEN]       (
3    [WORD]              aPoint
3    [MEMBER]            .
3    [WORD]              x
3    [FPAREN_CLOSE]      )
3    [ARITH]             +
3    [NUMBER_FP]         .5
3    [ARITH]             /
3    [WORD]              self
3    [MEMBER]            .
3    [WORD]              contentsScale
3    [ARITH]             +
3    [NUMBER]            3
3    [COMMA]             ,
3    [WORD]              aPoint
3    [MEMBER]            .
3    [WORD]              y
3    [ARITH]             -
3    [WORD]              aLength
3    [ARITH]             +
3    [NUMBER]            1
3    [ARITH]             +
3    [NUMBER]            4
3    [FPAREN_CLOSE]      )
3    [SEMICOLON]         ;
3    [NEWLINE]           