Line [Token]             Text
1    [TYPE]              byte
1    [TSQUARE]           []
1    [WORD]              utf8Str
1    [ASSIGN]            =
1    [NEW]               new
1    [TYPE]              byte
1    [TSQUARE]           []
1    [BRACE_OPEN]        {
1    [NUMBER]            197
1    [COMMA]             ,
1    [NUMBER]            170
1    [COMMA]             ,
1    [NUMBER]            110
1    [COMMA]             ,
1    [NUMBER]            196
1    [COMMA]             ,
1    [NUMBER]            173
1    [COMMA]             ,
1    [NUMBER]            099
1    [COMMA]             ,
1    [NUMBER]            197
1    [COMMA]             ,
1    [NUMBER]            141
1    [COMMA]             ,
1    [NUMBER]            100
1    [COMMA]             ,
1    [NUMBER]            101
1    [COMMA]             ,
1    [NUMBER]            204
1    [COMMA]             ,
1    [NUMBER]            189
1    [BRACE_CLOSE]       }
1    [SEMICOLON]         ;
1    [NEWLINE]           