Line [Token]             Text
1    [QUALIFIER]         public
1    [TYPE]              string
1    [WORD]              Foo
1    [LAMBDA]            =>
1    [NEWLINE]           
2    [STRING]            "bar"
2    [SEMICOLON]         ;
2    [NEWLINE]           
3    [QUALIFIER]         public
3    [TYPE]              string
3    [WORD]              Foo
3    [NEWLINE]           
4    [LAMBDA]            =>
4    [STRING]            "bar"
4    [SEMICOLON]         ;
4    [NEWLINE]           
6    [QUALIFIER]         public
6    [QUALIFIER]         static
6    [TYPE]              T
6    [FUNC_PROTO]        WithAdditionalFlags
6    [ANGLE_OPEN]        <
6    [TYPE]              T
6    [ANGLE_CLOSE]       >
6    [FPAREN_OPEN]       (
6    [THIS]              this
6    [TYPE]              T
6    [WORD]              _this
6    [COMMA]             ,
6    [TYPE]              IEnumerable
6    [ANGLE_OPEN]        <
6    [TYPE]              string
6    [ANGLE_CLOSE]       >
6    [WORD]              flags
6    [FPAREN_CLOSE]      )
6    [WHERE_SPEC]        where
6    [WORD]              T
6    [WHERE_COLON]       :
6    [WORD]              ObjectFileLinker
6    [NEWLINE]           
7    [LAMBDA]            =>
7    [WORD]              _this
7    [MEMBER]            .
7    [FUNC_CALL]         WithLinkerSetting
7    [FPAREN_OPEN]       (
7    [WORD]              l
7    [LAMBDA]            =>
7    [WORD]              l
7    [MEMBER]            .
7    [WORD]              Flags
7    [ASSIGN]            =
7    [WORD]              l
7    [MEMBER]            .
7    [WORD]              Flags
7    [MEMBER]            .
7    [FUNC_CALL]         Concat
7    [FPAREN_OPEN]       (
7    [WORD]              flags
7    [FPAREN_CLOSE]      )
7    [FPAREN_CLOSE]      )
7    [SEMICOLON]         ;
7    [NEWLINE]           
9    [QUALIFIER]         public
9    [QUALIFIER]         static
9    [TYPE]              T
9    [FUNC_PROTO]        WithAdditionalFlags
9    [ANGLE_OPEN]        <
9    [TYPE]              T
9    [ANGLE_CLOSE]       >
9    [FPAREN_OPEN]       (
9    [THIS]              this
9    [TYPE]              T
9    [WORD]              _this
9    [COMMA]             ,
9    [TYPE]              IEnumerable
9    [ANGLE_OPEN]        <
9    [TYPE]              string
9    [ANGLE_CLOSE]       >
9    [WORD]              flags
9    [FPAREN_CLOSE]      )
9    [WHERE_SPEC]        where
9    [WORD]              T
9    [WHERE_COLON]       :
9    [WORD]              ObjectFileLinker
9    [LAMBDA]            =>
9    [NEWLINE]           
10   [WORD]              _this
10   [MEMBER]            .
10   [FUNC_CALL]         WithLinkerSetting
10   [FPAREN_OPEN]       (
10   [WORD]              l
10   [LAMBDA]            =>
10   [WORD]              l
10   [MEMBER]            .
10   [WORD]              Flags
10   [ASSIGN]            =
10   [WORD]              l
10   [MEMBER]            .
10   [WORD]              Flags
10   [MEMBER]            .
10   [FUNC_CALL]         Concat
10   [FPAREN_OPEN]       (
10   [WORD]              flags
10   [FPAREN_CLOSE]      )
10   [FPAREN_CLOSE]      )
10   [SEMICOLON]         ;
10   [NEWLINE]           
12   [QUALIFIER]         public
12   [QUALIFIER]         static
12   [TYPE]              T
12   [FUNC_PROTO]        WithAdditionalFlags
12   [ANGLE_OPEN]        <
12   [TYPE]              T
12   [ANGLE_CLOSE]       >
12   [FPAREN_OPEN]       (
12   [THIS]              this
12   [TYPE]              T
12   [WORD]              _this
12   [COMMA]             ,
12   [TYPE]              IEnumerable
12   [ANGLE_OPEN]        <
12   [TYPE]              string
12   [ANGLE_CLOSE]       >
12   [WORD]              flags
12   [FPAREN_CLOSE]      )
12   [WHERE_SPEC]        where
12   [WORD]              T
12   [WHERE_COLON]       :
12   [WORD]              ObjectFileLinker
12   [NEWLINE]           
13   [LAMBDA]            =>
13   [WORD]              _this
13   [MEMBER]            .
13   [FUNC_CALL]         WithLinkerSetting
13   [FPAREN_OPEN]       (
13   [NEWLINE]           
14   [WORD]              l
14   [LAMBDA]            =>
14   [WORD]              l
14   [MEMBER]            .
14   [WORD]              Flags
14   [ASSIGN]            =
14   [NEWLINE]           
15   [WORD]              l
15   [MEMBER]            .
15   [WORD]              Flags
15   [MEMBER]            .
15   [FUNC_CALL]         Concat
15   [FPAREN_OPEN]       (
15   [WORD]              flags
15   [FPAREN_CLOSE]      )
15   [FPAREN_CLOSE]      )
15   [SEMICOLON]         ;
15   [NEWLINE]           
17   [QUALIFIER]         public
17   [QUALIFIER]         static
17   [TYPE]              T
17   [FUNC_PROTO]        WithAdditionalFlags
17   [ANGLE_OPEN]        <
17   [TYPE]              T
17   [ANGLE_CLOSE]       >
17   [FPAREN_OPEN]       (
17   [THIS]              this
17   [TYPE]              T
17   [WORD]              _this
17   [COMMA]             ,
17   [TYPE]              IEnumerable
17   [ANGLE_OPEN]        <
17   [TYPE]              string
17   [ANGLE_CLOSE]       >
17   [WORD]              flags
17   [FPAREN_CLOSE]      )
17   [WHERE_SPEC]        where
17   [WORD]              T
17   [WHERE_COLON]       :
17   [WORD]              ObjectFileLinker
17   [LAMBDA]            =>
17   [WORD]              _this
17   [MEMBER]            .
17   [FUNC_CALL]         WithLinkerSetting
17   [FPAREN_OPEN]       (
17   [NEWLINE]           
18   [WORD]              l
18   [LAMBDA]            =>
18   [WORD]              l
18   [MEMBER]            .
18   [WORD]              Flags
18   [ASSIGN]            =
18   [NEWLINE]           
19   [WORD]              l
19   [MEMBER]            .
19   [WORD]              Flags
19   [MEMBER]            .
19   [FUNC_CALL]         Concat
19   [FPAREN_OPEN]       (
19   [WORD]              flags
19   [FPAREN_CLOSE]      )
19   [FPAREN_CLOSE]      )
19   [SEMICOLON]         ;
19   [NEWLINE]           
21   [QUALIFIER]         public
21   [QUALIFIER]         static
21   [TYPE]              T
21   [FUNC_PROTO]        WithAdditionalFlags
21   [ANGLE_OPEN]        <
21   [TYPE]              T
21   [ANGLE_CLOSE]       >
21   [FPAREN_OPEN]       (
21   [THIS]              this
21   [TYPE]              T
21   [WORD]              _this
21   [COMMA]             ,
21   [TYPE]              IEnumerable
21   [ANGLE_OPEN]        <
21   [TYPE]              string
21   [ANGLE_CLOSE]       >
21   [WORD]              flags
21   [FPAREN_CLOSE]      )
21   [WHERE_SPEC]        where
21   [WORD]              T
21   [WHERE_COLON]       :
21   [WORD]              ObjectFileLinker
21   [NEWLINE]           
22   [LAMBDA]            =>
22   [WORD]              _this
22   [MEMBER]            .
22   [FUNC_CALL]         WithLinkerSetting
22   [FPAREN_OPEN]       (
22   [WORD]              l
22   [LAMBDA]            =>
22   [NEWLINE]           
23   [WORD]              l
23   [MEMBER]            .
23   [WORD]              Flags
23   [ASSIGN]            =
23   [WORD]              l
23   [MEMBER]            .
23   [WORD]              Flags
23   [MEMBER]            .
23   [FUNC_CALL]         Concat
23   [FPAREN_OPEN]       (
23   [WORD]              flags
23   [FPAREN_CLOSE]      )
23   [FPAREN_CLOSE]      )
23   [SEMICOLON]         ;
23   [NEWLINE]           
25   [QUALIFIER]         public
25   [QUALIFIER]         static
25   [TYPE]              T
25   [FUNC_PROTO]        WithAdditionalFlags
25   [ANGLE_OPEN]        <
25   [TYPE]              T
25   [ANGLE_CLOSE]       >
25   [FPAREN_OPEN]       (
25   [THIS]              this
25   [TYPE]              T
25   [WORD]              _this
25   [COMMA]             ,
25   [TYPE]              IEnumerable
25   [ANGLE_OPEN]        <
25   [TYPE]              string
25   [ANGLE_CLOSE]       >
25   [WORD]              flags
25   [FPAREN_CLOSE]      )
25   [WHERE_SPEC]        where
25   [WORD]              T
25   [WHERE_COLON]       :
25   [WORD]              ObjectFileLinker
25   [LAMBDA]            =>
25   [NEWLINE]           
26   [WORD]              _this
26   [MEMBER]            .
26   [FUNC_CALL]         WithLinkerSetting
26   [FPAREN_OPEN]       (
26   [WORD]              l
26   [NEWLINE]           
27   [LAMBDA]            =>
27   [WORD]              l
27   [MEMBER]            .
27   [WORD]              Flags
27   [ASSIGN]            =
27   [WORD]              l
27   [MEMBER]            .
27   [WORD]              Flags
27   [MEMBER]            .
27   [FUNC_CALL]         Concat
27   [FPAREN_OPEN]       (
27   [WORD]              flags
27   [FPAREN_CLOSE]      )
27   [FPAREN_CLOSE]      )
27   [SEMICOLON]         ;
27   [NEWLINE]           
29   [TYPE]              var
29   [WORD]              islands
29   [ASSIGN]            =
29   [WORD]              EditorCompilationInterface
29   [MEMBER]            .
29   [FUNC_CALL]         GetAllMonoIslands
29   [FPAREN_OPEN]       (
29   [FPAREN_CLOSE]      )
29   [MEMBER]            .
29   [FUNC_CALL]         Select
29   [FPAREN_OPEN]       (
29   [WORD]              i
29   [LAMBDA]            =>
29   [NEW]               new
29   [CS_PROPERTY]       Island
29   [NEWLINE]           
30   [BRACE_OPEN]        {
30   [NEWLINE]           
31   [WORD]              MonoIsland
31   [ASSIGN]            =
31   [WORD]              i
31   [COMMA]             ,
31   [NEWLINE]           
32   [WORD]              Name
32   [ASSIGN]            =
32   [WORD]              Path
32   [MEMBER]            .
32   [FUNC_CALL]         GetFileNameWithoutExtension
32   [FPAREN_OPEN]       (
32   [WORD]              i
32   [MEMBER]            .
32   [WORD]              _output
32   [FPAREN_CLOSE]      )
32   [COMMA]             ,
32   [NEWLINE]           
33   [WORD]              References
33   [ASSIGN]            =
33   [WORD]              i
33   [MEMBER]            .
33   [WORD]              _references
33   [MEMBER]            .
33   [FUNC_CALL]         ToList
33   [FPAREN_OPEN]       (
33   [FPAREN_CLOSE]      )
33   [NEWLINE]           
34   [BRACE_CLOSE]       }
34   [FPAREN_CLOSE]      )
34   [MEMBER]            .
34   [FUNC_CALL]         ToList
34   [FPAREN_OPEN]       (
34   [FPAREN_CLOSE]      )
34   [SEMICOLON]         ;
34   [NEWLINE]           
36   [TYPE]              var
36   [WORD]              projectEntries
36   [ASSIGN]            =
36   [WORD]              islands
36   [MEMBER]            .
36   [FUNC_CALL]         Select
36   [FPAREN_OPEN]       (
36   [WORD]              i
36   [LAMBDA]            =>
36   [TYPE]              string
36   [MEMBER]            .
36   [FUNC_CALL]         Format
36   [FPAREN_OPEN]       (
36   [NEWLINE]           
37   [WORD]              DefaultSynchronizationSettings
37   [MEMBER]            .
37   [WORD]              SolutionProjectEntryTemplate
37   [COMMA]             ,
37   [NEWLINE]           
38   [FUNC_CALL]         SolutionGuid
38   [FPAREN_OPEN]       (
38   [WORD]              i
38   [FPAREN_CLOSE]      )
38   [COMMA]             ,
38   [WORD]              _projectName
38   [COMMA]             ,
38   [WORD]              Path
38   [MEMBER]            .
38   [FUNC_CALL]         GetFileName
38   [FPAREN_OPEN]       (
38   [FUNC_CALL]         ProjectFile
38   [FPAREN_OPEN]       (
38   [WORD]              i
38   [FPAREN_CLOSE]      )
38   [FPAREN_CLOSE]      )
38   [COMMA]             ,
38   [FUNC_CALL]         ProjectGuid
38   [FPAREN_OPEN]       (
38   [WORD]              i
38   [MEMBER]            .
38   [WORD]              _output
38   [FPAREN_CLOSE]      )
38   [NEWLINE]           
39   [FPAREN_CLOSE]      )
39   [FPAREN_CLOSE]      )
39   [SEMICOLON]         ;
39   [NEWLINE]           
42   [TYPE]              Func
42   [ANGLE_OPEN]        <
42   [TYPE]              IEnumerable
42   [ANGLE_OPEN]        <
42   [TYPE]              IMemberDefinition
42   [ANGLE_CLOSE]       >
42   [COMMA]             ,
42   [TYPE]              IEnumerable
42   [ANGLE_OPEN]        <
42   [TYPE]              IMemberDefinition
42   [ANGLE_CLOSE]       >
42   [ANGLE_CLOSE]       >
42   [WORD]              filterMembersWithObsoleteAttr
42   [ASSIGN]            =
42   [WORD]              members
42   [LAMBDA]            =>
42   [WORD]              members
42   [MEMBER]            .
42   [FUNC_CALL]         Where
42   [FPAREN_OPEN]       (
42   [WORD]              m
42   [LAMBDA]            =>
42   [NEWLINE]           
43   [NOT]               !
43   [WORD]              m
43   [MEMBER]            .
43   [WORD]              IsRuntimeSpecialName
43   [NEWLINE]           
44   [BOOL]              &&
44   [NOT]               !
44   [WORD]              m
44   [MEMBER]            .
44   [WORD]              IsSpecialName
44   [NEWLINE]           
45   [BOOL]              &&
45   [NOT]               !
45   [WORD]              blackList
45   [MEMBER]            .
45   [FUNC_CALL]         Contains
45   [FPAREN_OPEN]       (
45   [WORD]              m
45   [MEMBER]            .
45   [WORD]              FullName
45   [FPAREN_CLOSE]      )
45   [NEWLINE]           
46   [BOOL]              &&
46   [FUNC_CALL]         CheckCustomAttributes
46   [FPAREN_OPEN]       (
46   [WORD]              m
46   [FPAREN_CLOSE]      )
46   [FPAREN_CLOSE]      )
46   [SEMICOLON]         ;
46   [NEWLINE]           